/// Qualified recovery and E3 to F3 review users from the same SmartInventory snapshot as the daily email.
table 'License Report Candidates'

	measure 'License Report Recovery Detail Rows' = CALCULATE(COUNTROWS('License Report Candidates'), 'License Report Candidates'[Candidate Type] = "Recovery")
		formatString: #,0
		displayFolder: Licensing | Mail parity

	measure 'License Report Downgrade Detail Rows' = CALCULATE(COUNTROWS('License Report Candidates'), 'License Report Candidates'[Candidate Type] = "E3 to F3 review")
		formatString: #,0
		displayFolder: Licensing | Mail parity

	column 'Snapshot ID'
		dataType: string
		sourceColumn: Snapshot ID

	column 'Tenant Key'
		dataType: string
		sourceColumn: Tenant Key

	column 'Candidate Type'
		dataType: string
		sourceColumn: Candidate Type

	column Product
		dataType: string
		sourceColumn: Product

	column 'User ID'
		dataType: string
		sourceColumn: User ID

	column 'User Principal Name'
		dataType: string
		sourceColumn: User Principal Name

	column 'Display Name'
		dataType: string
		sourceColumn: Display Name

	column Reason
		dataType: string
		sourceColumn: Reason

	column 'Last AD Activity Date'
		dataType: dateTime
		sourceColumn: Last AD Activity Date

	column 'Last M365 Activity Date'
		dataType: dateTime
		sourceColumn: Last M365 Activity Date

	column 'Primary On Intune PC'
		dataType: string
		sourceColumn: Primary On Intune PC

	column 'Target Suites'
		dataType: string
		sourceColumn: Target Suites

	column 'Mailbox Size GB'
		dataType: decimal
		sourceColumn: Mailbox Size GB

	column 'OneDrive Used GB'
		dataType: decimal
		sourceColumn: OneDrive Used GB

	partition 'License Report Candidates Import' = m
		mode: import
		source =
				let
				    Snapshot = GetLicenseReportSnapshot(),
				    DateOrNull = (value as any) => try DateTime.From(Date.FromText(Text.From(value), [Format="yyyy-MM-dd", Culture="en-US"])) otherwise null,
				    Recovery = List.Transform(Snapshot[RecoveryCandidates], each
				        [#"Snapshot ID"=Snapshot[SnapshotId], #"Tenant Key"=Snapshot[TenantKey], #"Candidate Type"="Recovery",
				         Product=_[License], #"User ID"=_[UserId], #"User Principal Name"=_[UserPrincipalName],
				         #"Display Name"=_[DisplayName], Reason=_[RecoveryReason],
				         #"Last AD Activity Date"=DateOrNull(_[LastAdActivityDate]), #"Last M365 Activity Date"=DateOrNull(_[LastM365ActivityDate]),
				         #"Primary On Intune PC"=_[PrimaryOnIntuneWindowsPc], #"Target Suites"=_[TargetSuites],
				         #"Mailbox Size GB"=null, #"OneDrive Used GB"=null]),
				    Downgrade = List.Transform(Snapshot[DowngradeCandidates], each
				        [#"Snapshot ID"=Snapshot[SnapshotId], #"Tenant Key"=Snapshot[TenantKey], #"Candidate Type"="E3 to F3 review",
				         Product="Microsoft 365 E3", #"User ID"=_[UserId], #"User Principal Name"=_[UserPrincipalName],
				         #"Display Name"=_[DisplayName], Reason="Manual downgrade review", #"Last AD Activity Date"=null,
				         #"Last M365 Activity Date"=null, #"Primary On Intune PC"=null, #"Target Suites"="Microsoft 365 E3",
				         #"Mailbox Size GB"=_[MailboxSizeGB], #"OneDrive Used GB"=_[OneDriveUsedGB]]),
				    Rows = Recovery & Downgrade,
				    Result = Table.FromRecords(Rows, type table [#"Snapshot ID"=text, #"Tenant Key"=text, #"Candidate Type"=text,
				        Product=text, #"User ID"=text, #"User Principal Name"=text, #"Display Name"=text, Reason=text,
				        #"Last AD Activity Date"=nullable datetime, #"Last M365 Activity Date"=nullable datetime,
				        #"Primary On Intune PC"=nullable text, #"Target Suites"=nullable text,
				        #"Mailbox Size GB"=nullable number, #"OneDrive Used GB"=nullable number])
				in
				    Result
