@{
    DefaultLanguage = 'en'
    Aliases = @{
        'en-US' = 'en'
        'en-GB' = 'en'
        'fr-FR' = 'fr'
        'fr-BE' = 'fr'
        'fr-CA' = 'fr'
        'de-DE' = 'de'
        'de-AT' = 'de'
        'de-CH' = 'de'
        'es-ES' = 'es'
        'es-MX' = 'es'
        'nl-NL' = 'nl'
        'nl-BE' = 'nl'
        'it-IT' = 'it'
        'pt-PT' = 'pt'
        'pt-BR' = 'pt'
        'pl-PL' = 'pl'
        'ar-SA' = 'ar'
        'ar-AE' = 'ar'
        'tr-TR' = 'tr'
        'sv-SE' = 'sv'
        'da-DK' = 'da'
        'nb-NO' = 'nb'
        'no' = 'nb'
        'fi-FI' = 'fi'
        'ro-RO' = 'ro'
        'hu-HU' = 'hu'
        'ja-JP' = 'ja'
        'ko-KR' = 'ko'
        'zh' = 'zh-Hans'
        'zh-CN' = 'zh-Hans'
        'zh-SG' = 'zh-Hans'
        'zh-Hans-CN' = 'zh-Hans'
        'uk-UA' = 'uk'
    }
    LanguageNames = @{
        en = 'English'
        fr = 'Français'
        de = 'Deutsch'
        es = 'Español'
        nl = 'Nederlands'
        it = 'Italiano'
        pt = 'Português'
        pl = 'Polski'
        ar = 'العربية'
        tr = 'Türkçe'
        sv = 'Svenska'
        da = 'Dansk'
        nb = 'Norsk'
        fi = 'Suomi'
        ro = 'Română'
        hu = 'Magyar'
        ja = '日本語'
        ko = '한국어'
        'zh-Hans' = '简体中文'
        uk = 'Українська'
    }
    Strings = @{
        en = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'Restart required'
            PillRecommended = 'Restart recommended'
            ForcedTitle = 'A restart is now required'
            RecommendedTitle = 'A restart is recommended'
            ForcedSummary = 'This device has exceeded the maximum allowed uptime. Save your work now; the restart timer is active.'
            RecommendedSummary = 'Restarting regularly helps apply updates and keeps the device stable.'
            RestartNow = 'Restart now'
            RemindLater = 'Remind me later'
            Postpone = 'Postpone'
            Preview = 'Preview mode'
            Countdown = 'Automatic restart in {0:D2}:{1:D2}'
            NoCountdown = 'No automatic restart is scheduled in recommendation mode.'
            Uptime = 'Uptime'
            Threshold = 'Recommendation'
            Maximum = 'Required'
            LastBoot = 'Last boot'
            NextActionForced = 'Restart before the countdown reaches zero.'
            NextActionRecommended = 'Choose a convenient moment to restart.'
            Activity = 'Activity'
            ConfirmRestart = 'Restart this device now? Save your work before continuing.'
            Close = 'Close'
            DaysUnit = 'days'
            ShowingGui = 'Showing Smart Device Reboot Manager GUI.'
            ClosedGui = 'Smart Device Reboot Manager GUI closed.'
            LanguageLabel = 'Language'
            LanguageAuto = 'Automatic'
        }
        fr = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'SmartM365 Gestionnaire de redémarrage'
            PillForced = 'Redémarrage obligatoire'
            PillRecommended = 'Redémarrage recommandé'
            ForcedTitle = 'Un redémarrage est maintenant requis'
            RecommendedTitle = 'Un redémarrage est recommandé'
            ForcedSummary = 'Cet appareil a dépassé la durée maximale autorisée sans redémarrage. Enregistrez vos travaux; le compte à rebours est actif.'
            RecommendedSummary = 'Un redémarrage régulier applique les mises à jour et maintient la stabilité du poste.'
            RestartNow = 'Redémarrer maintenant'
            RemindLater = 'Me le rappeler plus tard'
            Postpone = 'Reporter'
            Preview = 'Mode aperçu'
            Countdown = 'Redémarrage automatique dans {0:D2}:{1:D2}'
            NoCountdown = 'Aucun redémarrage automatique en mode recommandation.'
            Uptime = 'Durée depuis redémarrage'
            Threshold = 'Recommandation'
            Maximum = 'Obligatoire'
            LastBoot = 'Dernier démarrage'
            NextActionForced = 'Redémarrez avant la fin du compte à rebours.'
            NextActionRecommended = 'Choisissez un moment pratique pour redémarrer.'
            Activity = 'Activité'
            ConfirmRestart = 'Redémarrer cet appareil maintenant ? Enregistrez vos travaux avant de continuer.'
            Close = 'Fermer'
            DaysUnit = 'jours'
            ShowingGui = 'Affichage de Smart Device Reboot Manager.'
            ClosedGui = 'Smart Device Reboot Manager fermé.'
            LanguageLabel = 'Langue'
            LanguageAuto = 'Automatique'
        }
        de = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'Neustart erforderlich'
            PillRecommended = 'Neustart empfohlen'
            ForcedTitle = 'Ein Neustart ist jetzt erforderlich'
            RecommendedTitle = 'Ein Neustart wird empfohlen'
            ForcedSummary = 'Dieses Gerät hat die maximal zulässige Laufzeit überschritten. Speichern Sie Ihre Arbeit; der Neustart-Timer läuft.'
            RecommendedSummary = 'Regelmäßige Neustarts helfen, Updates anzuwenden und das Gerät stabil zu halten.'
            RestartNow = 'Jetzt neu starten'
            RemindLater = 'Später erinnern'
            Postpone = 'Verschieben'
            Preview = 'Vorschaumodus'
            Countdown = 'Automatischer Neustart in {0:D2}:{1:D2}'
            NoCountdown = 'Im Empfehlungsmodus ist kein automatischer Neustart geplant.'
            Uptime = 'Laufzeit'
            Threshold = 'Empfehlung'
            Maximum = 'Erforderlich'
            LastBoot = 'Letzter Start'
            NextActionForced = 'Starten Sie neu, bevor der Countdown null erreicht.'
            NextActionRecommended = 'Wählen Sie einen passenden Zeitpunkt für den Neustart.'
            Activity = 'Aktivität'
            ConfirmRestart = 'Dieses Gerät jetzt neu starten? Speichern Sie Ihre Arbeit, bevor Sie fortfahren.'
            Close = 'Schließen'
            DaysUnit = 'Tage'
            ShowingGui = 'Smart Device Reboot Manager wird angezeigt.'
            ClosedGui = 'Smart Device Reboot Manager wurde geschlossen.'
            LanguageLabel = 'Sprache'
            LanguageAuto = 'Automatisch'
        }
        es = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'Reinicio obligatorio'
            PillRecommended = 'Reinicio recomendado'
            ForcedTitle = 'Ahora se requiere un reinicio'
            RecommendedTitle = 'Se recomienda reiniciar'
            ForcedSummary = 'Este dispositivo ha superado el tiempo máximo permitido sin reiniciar. Guarde su trabajo; el temporizador está activo.'
            RecommendedSummary = 'Reiniciar con regularidad ayuda a aplicar actualizaciones y mantener estable el dispositivo.'
            RestartNow = 'Reiniciar ahora'
            RemindLater = 'Recordarme más tarde'
            Postpone = 'Posponer'
            Preview = 'Modo de vista previa'
            Countdown = 'Reinicio automático en {0:D2}:{1:D2}'
            NoCountdown = 'No hay reinicio automático programado en modo de recomendación.'
            Uptime = 'Tiempo activo'
            Threshold = 'Recomendación'
            Maximum = 'Obligatorio'
            LastBoot = 'Último arranque'
            NextActionForced = 'Reinicie antes de que la cuenta atrás llegue a cero.'
            NextActionRecommended = 'Elija un momento adecuado para reiniciar.'
            Activity = 'Actividad'
            ConfirmRestart = '¿Reiniciar este dispositivo ahora? Guarde su trabajo antes de continuar.'
            Close = 'Cerrar'
            DaysUnit = 'días'
            ShowingGui = 'Mostrando Smart Device Reboot Manager.'
            ClosedGui = 'Smart Device Reboot Manager cerrado.'
            LanguageLabel = 'Idioma'
            LanguageAuto = 'Automático'
        }
        nl = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'Herstart vereist'
            PillRecommended = 'Herstart aanbevolen'
            ForcedTitle = 'Een herstart is nu vereist'
            RecommendedTitle = 'Een herstart wordt aanbevolen'
            ForcedSummary = 'Dit apparaat heeft de maximaal toegestane uptime overschreden. Sla uw werk op; de herstarttimer loopt.'
            RecommendedSummary = 'Regelmatig herstarten helpt updates toe te passen en het apparaat stabiel te houden.'
            RestartNow = 'Nu herstarten'
            RemindLater = 'Herinner mij later'
            Postpone = 'Uitstellen'
            Preview = 'Voorbeeldmodus'
            Countdown = 'Automatische herstart over {0:D2}:{1:D2}'
            NoCountdown = 'Er is geen automatische herstart gepland in aanbevelingsmodus.'
            Uptime = 'Uptime'
            Threshold = 'Aanbeveling'
            Maximum = 'Vereist'
            LastBoot = 'Laatste start'
            NextActionForced = 'Herstart voordat de teller nul bereikt.'
            NextActionRecommended = 'Kies een geschikt moment om te herstarten.'
            Activity = 'Activiteit'
            ConfirmRestart = 'Dit apparaat nu herstarten? Sla uw werk op voordat u doorgaat.'
            Close = 'Sluiten'
            DaysUnit = 'dagen'
            ShowingGui = 'Smart Device Reboot Manager wordt weergegeven.'
            ClosedGui = 'Smart Device Reboot Manager gesloten.'
            LanguageLabel = 'Taal'
            LanguageAuto = 'Automatisch'
        }
        it = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'Riavvio obbligatorio'
            PillRecommended = 'Riavvio consigliato'
            ForcedTitle = 'Ora è necessario un riavvio'
            RecommendedTitle = 'Si consiglia un riavvio'
            ForcedSummary = 'Questo dispositivo ha superato il tempo massimo consentito senza riavvio. Salvare il lavoro; il timer è attivo.'
            RecommendedSummary = 'Riavvii regolari aiutano ad applicare gli aggiornamenti e mantenere stabile il dispositivo.'
            RestartNow = 'Riavvia ora'
            RemindLater = 'Ricordamelo più tardi'
            Postpone = 'Posticipa'
            Preview = 'Modalità anteprima'
            Countdown = 'Riavvio automatico tra {0:D2}:{1:D2}'
            NoCountdown = 'Nessun riavvio automatico è pianificato in modalità raccomandazione.'
            Uptime = 'Tempo di attività'
            Threshold = 'Raccomandazione'
            Maximum = 'Obbligatorio'
            LastBoot = 'Ultimo avvio'
            NextActionForced = 'Riavviare prima che il conto alla rovescia arrivi a zero.'
            NextActionRecommended = 'Scegliere un momento adatto per riavviare.'
            Activity = 'Attività'
            ConfirmRestart = 'Riavviare questo dispositivo ora? Salvare il lavoro prima di continuare.'
            Close = 'Chiudi'
            DaysUnit = 'giorni'
            ShowingGui = 'Smart Device Reboot Manager visualizzato.'
            ClosedGui = 'Smart Device Reboot Manager chiuso.'
            LanguageLabel = 'Lingua'
            LanguageAuto = 'Automatico'
        }
        pt = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'Reinício obrigatório'
            PillRecommended = 'Reinício recomendado'
            ForcedTitle = 'Agora é necessário reiniciar'
            RecommendedTitle = 'Recomenda-se reiniciar'
            ForcedSummary = 'Este dispositivo excedeu o tempo máximo permitido sem reiniciar. Guarde o seu trabalho; o temporizador está ativo.'
            RecommendedSummary = 'Reinícios regulares ajudam a aplicar atualizações e manter o dispositivo estável.'
            RestartNow = 'Reiniciar agora'
            RemindLater = 'Lembrar mais tarde'
            Postpone = 'Adiar'
            Preview = 'Modo de pré-visualização'
            Countdown = 'Reinício automático em {0:D2}:{1:D2}'
            NoCountdown = 'Nenhum reinício automático está agendado no modo de recomendação.'
            Uptime = 'Tempo ligado'
            Threshold = 'Recomendação'
            Maximum = 'Obrigatório'
            LastBoot = 'Último arranque'
            NextActionForced = 'Reinicie antes que a contagem chegue a zero.'
            NextActionRecommended = 'Escolha um momento conveniente para reiniciar.'
            Activity = 'Atividade'
            ConfirmRestart = 'Reiniciar este dispositivo agora? Guarde o seu trabalho antes de continuar.'
            Close = 'Fechar'
            DaysUnit = 'dias'
            ShowingGui = 'A apresentar o Smart Device Reboot Manager.'
            ClosedGui = 'Smart Device Reboot Manager fechado.'
            LanguageLabel = 'Idioma'
            LanguageAuto = 'Automático'
        }
        pl = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'Wymagany restart'
            PillRecommended = 'Zalecany restart'
            ForcedTitle = 'Restart jest teraz wymagany'
            RecommendedTitle = 'Zaleca się restart'
            ForcedSummary = 'To urządzenie przekroczyło maksymalny dozwolony czas pracy. Zapisz pracę; licznik restartu jest aktywny.'
            RecommendedSummary = 'Regularne restarty pomagają stosować aktualizacje i utrzymać stabilność urządzenia.'
            RestartNow = 'Uruchom ponownie teraz'
            RemindLater = 'Przypomnij później'
            Postpone = 'Odłóż'
            Preview = 'Tryb podglądu'
            Countdown = 'Automatyczny restart za {0:D2}:{1:D2}'
            NoCountdown = 'W trybie zalecenia nie zaplanowano automatycznego restartu.'
            Uptime = 'Czas pracy'
            Threshold = 'Zalecenie'
            Maximum = 'Wymagane'
            LastBoot = 'Ostatni start'
            NextActionForced = 'Uruchom ponownie, zanim licznik dojdzie do zera.'
            NextActionRecommended = 'Wybierz dogodny moment na restart.'
            Activity = 'Aktywność'
            ConfirmRestart = 'Uruchomić to urządzenie ponownie teraz? Zapisz pracę przed kontynuacją.'
            Close = 'Zamknij'
            DaysUnit = 'dni'
            ShowingGui = 'Wyświetlanie Smart Device Reboot Manager.'
            ClosedGui = 'Smart Device Reboot Manager zamknięty.'
            LanguageLabel = 'Język'
            LanguageAuto = 'Automatycznie'
        }
        ar = @{
            FlowDirection = 'RightToLeft'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'إعادة التشغيل مطلوبة'
            PillRecommended = 'يوصى بإعادة التشغيل'
            ForcedTitle = 'إعادة التشغيل مطلوبة الآن'
            RecommendedTitle = 'يوصى بإعادة تشغيل الجهاز'
            ForcedSummary = 'تجاوز هذا الجهاز مدة التشغيل القصوى المسموح بها. احفظ عملك الآن؛ مؤقت إعادة التشغيل نشط.'
            RecommendedSummary = 'تساعد إعادة التشغيل المنتظمة على تطبيق التحديثات والحفاظ على استقرار الجهاز.'
            RestartNow = 'إعادة التشغيل الآن'
            RemindLater = 'تذكيري لاحقًا'
            Postpone = 'تأجيل'
            Preview = 'وضع المعاينة'
            Countdown = 'إعادة تشغيل تلقائية خلال {0:D2}:{1:D2}'
            NoCountdown = 'لا توجد إعادة تشغيل تلقائية مجدولة في وضع التوصية.'
            Uptime = 'مدة التشغيل'
            Threshold = 'التوصية'
            Maximum = 'مطلوب'
            LastBoot = 'آخر تشغيل'
            NextActionForced = 'أعد التشغيل قبل أن يصل العد التنازلي إلى الصفر.'
            NextActionRecommended = 'اختر وقتًا مناسبًا لإعادة التشغيل.'
            Activity = 'النشاط'
            ConfirmRestart = 'هل تريد إعادة تشغيل هذا الجهاز الآن؟ احفظ عملك قبل المتابعة.'
            Close = 'إغلاق'
            DaysUnit = 'أيام'
            ShowingGui = 'يتم عرض Smart Device Reboot Manager.'
            ClosedGui = 'تم إغلاق Smart Device Reboot Manager.'
            LanguageLabel = 'اللغة'
            LanguageAuto = 'تلقائي'
        }
        tr = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'Yeniden başlatma gerekli'
            PillRecommended = 'Yeniden başlatma önerilir'
            ForcedTitle = 'Şimdi yeniden başlatma gerekiyor'
            RecommendedTitle = 'Yeniden başlatma önerilir'
            ForcedSummary = 'Bu cihaz izin verilen en uzun çalışma süresini aştı. Çalışmanızı kaydedin; sayaç aktif.'
            RecommendedSummary = 'Düzenli yeniden başlatmalar güncellemeleri uygular ve cihazı kararlı tutar.'
            RestartNow = 'Şimdi yeniden başlat'
            RemindLater = 'Daha sonra hatırlat'
            Postpone = 'Ertele'
            Preview = 'Önizleme modu'
            Countdown = 'Otomatik yeniden başlatma {0:D2}:{1:D2} içinde'
            NoCountdown = 'Öneri modunda otomatik yeniden başlatma planlanmaz.'
            Uptime = 'Çalışma süresi'
            Threshold = 'Öneri'
            Maximum = 'Zorunlu'
            LastBoot = 'Son başlatma'
            NextActionForced = 'Sayaç sıfıra ulaşmadan önce yeniden başlatın.'
            NextActionRecommended = 'Yeniden başlatmak için uygun bir zaman seçin.'
            Activity = 'Etkinlik'
            ConfirmRestart = 'Bu cihaz şimdi yeniden başlatılsın mı? Devam etmeden önce çalışmanızı kaydedin.'
            Close = 'Kapat'
            DaysUnit = 'gün'
            ShowingGui = 'Smart Device Reboot Manager gösteriliyor.'
            ClosedGui = 'Smart Device Reboot Manager kapatıldı.'
            LanguageLabel = 'Dil'
            LanguageAuto = 'Otomatik'
        }
        sv = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'Omstart krävs'
            PillRecommended = 'Omstart rekommenderas'
            ForcedTitle = 'En omstart krävs nu'
            RecommendedTitle = 'En omstart rekommenderas'
            ForcedSummary = 'Den här enheten har överskridit maximal tillåten drifttid. Spara ditt arbete; omstartstimern är aktiv.'
            RecommendedSummary = 'Regelbundna omstarter hjälper till att tillämpa uppdateringar och hålla enheten stabil.'
            RestartNow = 'Starta om nu'
            RemindLater = 'Påminn mig senare'
            Postpone = 'Skjut upp'
            Preview = 'Förhandsläge'
            Countdown = 'Automatisk omstart om {0:D2}:{1:D2}'
            NoCountdown = 'Ingen automatisk omstart är schemalagd i rekommendationsläge.'
            Uptime = 'Drifttid'
            Threshold = 'Rekommendation'
            Maximum = 'Krävs'
            LastBoot = 'Senaste start'
            NextActionForced = 'Starta om innan nedräkningen når noll.'
            NextActionRecommended = 'Välj en lämplig tidpunkt för omstart.'
            Activity = 'Aktivitet'
            ConfirmRestart = 'Starta om den här enheten nu? Spara ditt arbete innan du fortsätter.'
            Close = 'Stäng'
            DaysUnit = 'dagar'
            ShowingGui = 'Smart Device Reboot Manager visas.'
            ClosedGui = 'Smart Device Reboot Manager stängdes.'
            LanguageLabel = 'Språk'
            LanguageAuto = 'Automatiskt'
        }
        da = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'Genstart påkrævet'
            PillRecommended = 'Genstart anbefales'
            ForcedTitle = 'En genstart er nu påkrævet'
            RecommendedTitle = 'En genstart anbefales'
            ForcedSummary = 'Denne enhed har overskredet den maksimalt tilladte oppetid. Gem dit arbejde; genstartstimeren er aktiv.'
            RecommendedSummary = 'Regelmæssige genstarter hjælper med at anvende opdateringer og holde enheden stabil.'
            RestartNow = 'Genstart nu'
            RemindLater = 'Påmind mig senere'
            Postpone = 'Udskyd'
            Preview = 'Forhåndsvisning'
            Countdown = 'Automatisk genstart om {0:D2}:{1:D2}'
            NoCountdown = 'Ingen automatisk genstart er planlagt i anbefalingstilstand.'
            Uptime = 'Oppetid'
            Threshold = 'Anbefaling'
            Maximum = 'Påkrævet'
            LastBoot = 'Seneste start'
            NextActionForced = 'Genstart før nedtællingen når nul.'
            NextActionRecommended = 'Vælg et passende tidspunkt at genstarte.'
            Activity = 'Aktivitet'
            ConfirmRestart = 'Genstart denne enhed nu? Gem dit arbejde, før du fortsætter.'
            Close = 'Luk'
            DaysUnit = 'dage'
            ShowingGui = 'Smart Device Reboot Manager vises.'
            ClosedGui = 'Smart Device Reboot Manager blev lukket.'
            LanguageLabel = 'Sprog'
            LanguageAuto = 'Automatisk'
        }
        nb = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'Omstart kreves'
            PillRecommended = 'Omstart anbefales'
            ForcedTitle = 'En omstart kreves nå'
            RecommendedTitle = 'En omstart anbefales'
            ForcedSummary = 'Denne enheten har overskredet maksimal tillatt oppetid. Lagre arbeidet ditt; omstartstimeren er aktiv.'
            RecommendedSummary = 'Regelmessige omstarter hjelper med å bruke oppdateringer og holde enheten stabil.'
            RestartNow = 'Start på nytt nå'
            RemindLater = 'Påminn meg senere'
            Postpone = 'Utsett'
            Preview = 'Forhåndsvisning'
            Countdown = 'Automatisk omstart om {0:D2}:{1:D2}'
            NoCountdown = 'Ingen automatisk omstart er planlagt i anbefalingsmodus.'
            Uptime = 'Oppetid'
            Threshold = 'Anbefaling'
            Maximum = 'Kreves'
            LastBoot = 'Siste start'
            NextActionForced = 'Start på nytt før nedtellingen når null.'
            NextActionRecommended = 'Velg et passende tidspunkt for omstart.'
            Activity = 'Aktivitet'
            ConfirmRestart = 'Starte denne enheten på nytt nå? Lagre arbeidet ditt før du fortsetter.'
            Close = 'Lukk'
            DaysUnit = 'dager'
            ShowingGui = 'Smart Device Reboot Manager vises.'
            ClosedGui = 'Smart Device Reboot Manager lukket.'
            LanguageLabel = 'Språk'
            LanguageAuto = 'Automatisk'
        }
        fi = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'Uudelleenkäynnistys vaaditaan'
            PillRecommended = 'Uudelleenkäynnistystä suositellaan'
            ForcedTitle = 'Uudelleenkäynnistys vaaditaan nyt'
            RecommendedTitle = 'Uudelleenkäynnistystä suositellaan'
            ForcedSummary = 'Tämä laite on ylittänyt suurimman sallitun käyttöajan. Tallenna työsi; ajastin on käynnissä.'
            RecommendedSummary = 'Säännölliset uudelleenkäynnistykset auttavat asentamaan päivitykset ja pitämään laitteen vakaana.'
            RestartNow = 'Käynnistä uudelleen nyt'
            RemindLater = 'Muistuta myöhemmin'
            Postpone = 'Lykkää'
            Preview = 'Esikatselutila'
            Countdown = 'Automaattinen uudelleenkäynnistys {0:D2}:{1:D2} kuluttua'
            NoCountdown = 'Suositustilassa ei ole ajastettua automaattista uudelleenkäynnistystä.'
            Uptime = 'Käyttöaika'
            Threshold = 'Suositus'
            Maximum = 'Vaaditaan'
            LastBoot = 'Viimeisin käynnistys'
            NextActionForced = 'Käynnistä uudelleen ennen kuin laskuri saavuttaa nollan.'
            NextActionRecommended = 'Valitse sopiva hetki uudelleenkäynnistykselle.'
            Activity = 'Toiminta'
            ConfirmRestart = 'Käynnistetäänkö tämä laite uudelleen nyt? Tallenna työsi ennen jatkamista.'
            Close = 'Sulje'
            DaysUnit = 'päivää'
            ShowingGui = 'Smart Device Reboot Manager näytetään.'
            ClosedGui = 'Smart Device Reboot Manager suljettu.'
            LanguageLabel = 'Kieli'
            LanguageAuto = 'Automaattinen'
        }
        ro = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'Repornire necesară'
            PillRecommended = 'Repornire recomandată'
            ForcedTitle = 'Acum este necesară o repornire'
            RecommendedTitle = 'Se recomandă o repornire'
            ForcedSummary = 'Acest dispozitiv a depășit durata maximă permisă de funcționare. Salvați lucrul; cronometrul este activ.'
            RecommendedSummary = 'Repornirile regulate ajută la aplicarea actualizărilor și mențin dispozitivul stabil.'
            RestartNow = 'Repornește acum'
            RemindLater = 'Amintește-mi mai târziu'
            Postpone = 'Amână'
            Preview = 'Mod previzualizare'
            Countdown = 'Repornire automată în {0:D2}:{1:D2}'
            NoCountdown = 'Nu este programată nicio repornire automată în modul recomandare.'
            Uptime = 'Timp de funcționare'
            Threshold = 'Recomandare'
            Maximum = 'Necesar'
            LastBoot = 'Ultima pornire'
            NextActionForced = 'Reporniți înainte ca numărătoarea inversă să ajungă la zero.'
            NextActionRecommended = 'Alegeți un moment potrivit pentru repornire.'
            Activity = 'Activitate'
            ConfirmRestart = 'Reporniți acest dispozitiv acum? Salvați lucrul înainte de a continua.'
            Close = 'Închide'
            DaysUnit = 'zile'
            ShowingGui = 'Se afișează Smart Device Reboot Manager.'
            ClosedGui = 'Smart Device Reboot Manager închis.'
            LanguageLabel = 'Limbă'
            LanguageAuto = 'Automat'
        }
        hu = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'Újraindítás szükséges'
            PillRecommended = 'Újraindítás javasolt'
            ForcedTitle = 'Most újraindítás szükséges'
            RecommendedTitle = 'Újraindítás javasolt'
            ForcedSummary = 'Ez az eszköz túllépte a megengedett maximális üzemidőt. Mentse a munkáját; az időzítő aktív.'
            RecommendedSummary = 'A rendszeres újraindítás segít a frissítések alkalmazásában és az eszköz stabil működésében.'
            RestartNow = 'Újraindítás most'
            RemindLater = 'Emlékeztessen később'
            Postpone = 'Elhalasztás'
            Preview = 'Előnézeti mód'
            Countdown = 'Automatikus újraindítás {0:D2}:{1:D2} múlva'
            NoCountdown = 'Ajánlási módban nincs automatikus újraindítás ütemezve.'
            Uptime = 'Üzemidő'
            Threshold = 'Ajánlás'
            Maximum = 'Kötelező'
            LastBoot = 'Utolsó indítás'
            NextActionForced = 'Indítsa újra, mielőtt a visszaszámlálás eléri a nullát.'
            NextActionRecommended = 'Válasszon megfelelő időpontot az újraindításhoz.'
            Activity = 'Tevékenység'
            ConfirmRestart = 'Újraindítja most ezt az eszközt? Mentse a munkáját a folytatás előtt.'
            Close = 'Bezárás'
            DaysUnit = 'nap'
            ShowingGui = 'A Smart Device Reboot Manager megjelenítése.'
            ClosedGui = 'Smart Device Reboot Manager bezárva.'
            LanguageLabel = 'Nyelv'
            LanguageAuto = 'Automatikus'
        }
        ja = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = '再起動が必要です'
            PillRecommended = '再起動を推奨します'
            ForcedTitle = '再起動が必要です'
            RecommendedTitle = '再起動をお勧めします'
            ForcedSummary = 'このデバイスは許可された最大稼働時間を超えました。作業を保存してください。再起動タイマーが動作しています。'
            RecommendedSummary = '定期的な再起動は更新プログラムの適用とデバイスの安定性維持に役立ちます。'
            RestartNow = '今すぐ再起動'
            RemindLater = '後で通知'
            Postpone = '延期'
            Preview = 'プレビューモード'
            Countdown = '{0:D2}:{1:D2} 後に自動再起動'
            NoCountdown = '推奨モードでは自動再起動は予定されていません。'
            Uptime = '稼働時間'
            Threshold = '推奨'
            Maximum = '必須'
            LastBoot = '前回の起動'
            NextActionForced = 'カウントダウンがゼロになる前に再起動してください。'
            NextActionRecommended = '都合のよいタイミングで再起動してください。'
            Activity = 'アクティビティ'
            ConfirmRestart = 'このデバイスを今すぐ再起動しますか? 続行する前に作業を保存してください。'
            Close = '閉じる'
            DaysUnit = '日'
            ShowingGui = 'Smart Device Reboot Manager を表示しています。'
            ClosedGui = 'Smart Device Reboot Manager を閉じました。'
            LanguageLabel = '言語'
            LanguageAuto = '自動'
        }
        ko = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = '다시 시작 필요'
            PillRecommended = '다시 시작 권장'
            ForcedTitle = '지금 다시 시작해야 합니다'
            RecommendedTitle = '다시 시작을 권장합니다'
            ForcedSummary = '이 장치는 허용된 최대 가동 시간을 초과했습니다. 작업을 저장하세요. 다시 시작 타이머가 실행 중입니다.'
            RecommendedSummary = '정기적인 다시 시작은 업데이트 적용과 장치 안정성 유지에 도움이 됩니다.'
            RestartNow = '지금 다시 시작'
            RemindLater = '나중에 알림'
            Postpone = '연기'
            Preview = '미리 보기 모드'
            Countdown = '{0:D2}:{1:D2} 후 자동 다시 시작'
            NoCountdown = '권장 모드에서는 자동 다시 시작이 예약되어 있지 않습니다.'
            Uptime = '가동 시간'
            Threshold = '권장'
            Maximum = '필수'
            LastBoot = '마지막 부팅'
            NextActionForced = '카운트다운이 0이 되기 전에 다시 시작하세요.'
            NextActionRecommended = '편리한 시간에 다시 시작하세요.'
            Activity = '활동'
            ConfirmRestart = '이 장치를 지금 다시 시작할까요? 계속하기 전에 작업을 저장하세요.'
            Close = '닫기'
            DaysUnit = '일'
            ShowingGui = 'Smart Device Reboot Manager를 표시합니다.'
            ClosedGui = 'Smart Device Reboot Manager를 닫았습니다.'
            LanguageLabel = '언어'
            LanguageAuto = '자동'
        }
        'zh-Hans' = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = '需要重启'
            PillRecommended = '建议重启'
            ForcedTitle = '现在需要重启'
            RecommendedTitle = '建议重启设备'
            ForcedSummary = '此设备已超过允许的最长运行时间。请立即保存工作；重启计时器已启动。'
            RecommendedSummary = '定期重启有助于应用更新并保持设备稳定。'
            RestartNow = '立即重启'
            RemindLater = '稍后提醒我'
            Postpone = '推迟'
            Preview = '预览模式'
            Countdown = '{0:D2}:{1:D2} 后自动重启'
            NoCountdown = '建议模式下未计划自动重启。'
            Uptime = '运行时间'
            Threshold = '建议'
            Maximum = '必需'
            LastBoot = '上次启动'
            NextActionForced = '请在倒计时归零前重启。'
            NextActionRecommended = '请选择合适的时间重启。'
            Activity = '活动'
            ConfirmRestart = '现在重启此设备吗？继续前请保存工作。'
            Close = '关闭'
            DaysUnit = '天'
            ShowingGui = '正在显示 Smart Device Reboot Manager。'
            ClosedGui = 'Smart Device Reboot Manager 已关闭。'
            LanguageLabel = '语言'
            LanguageAuto = '自动'
        }
        uk = @{
            FlowDirection = 'LeftToRight'
            WindowTitle = 'Smart Device Reboot Manager'
            PillForced = 'Потрібне перезавантаження'
            PillRecommended = 'Рекомендовано перезавантаження'
            ForcedTitle = 'Зараз потрібне перезавантаження'
            RecommendedTitle = 'Рекомендовано перезавантажити пристрій'
            ForcedSummary = 'Цей пристрій перевищив максимально дозволений час роботи. Збережіть роботу; таймер перезавантаження активний.'
            RecommendedSummary = 'Регулярні перезавантаження допомагають застосовувати оновлення та підтримувати стабільність пристрою.'
            RestartNow = 'Перезавантажити зараз'
            RemindLater = 'Нагадати пізніше'
            Postpone = 'Відкласти'
            Preview = 'Режим попереднього перегляду'
            Countdown = 'Автоматичне перезавантаження через {0:D2}:{1:D2}'
            NoCountdown = 'В режимі рекомендації автоматичне перезавантаження не заплановано.'
            Uptime = 'Час роботи'
            Threshold = 'Рекомендація'
            Maximum = 'Необхідно'
            LastBoot = 'Останній запуск'
            NextActionForced = 'Перезавантажте пристрій до завершення відліку.'
            NextActionRecommended = 'Виберіть зручний час для перезавантаження.'
            Activity = 'Активність'
            ConfirmRestart = 'Перезавантажити цей пристрій зараз? Збережіть роботу перед продовженням.'
            Close = 'Закрити'
            DaysUnit = 'днів'
            ShowingGui = 'Відображається Smart Device Reboot Manager.'
            ClosedGui = 'Smart Device Reboot Manager закрито.'
            LanguageLabel = 'Мова'
            LanguageAuto = 'Автоматично'
        }
    }
}







# SIG # Begin signature block
# MIIHcgYJKoZIhvcNAQcCoIIHYzCCB18CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCAonKu6h86XLeKJ
# 9M89a8I64zyht9YHUFNwF+xeWbOMd6CCBEgwggREMIICrKADAgECAhBxu0EivlCF
# tUbJPfe/Va5qMA0GCSqGSIb3DQEBCwUAMDoxODA2BgNVBAMML1NtYXJ0TTM2NSBP
# cmNoZXN0cmF0b3IgQ29kZSBTaWduaW5nIFNlbGYtU2lnbmVkMB4XDTI2MDcxMTIz
# MTc1MloXDTI5MDcxMTIzMjc1MVowOjE4MDYGA1UEAwwvU21hcnRNMzY1IE9yY2hl
# c3RyYXRvciBDb2RlIFNpZ25pbmcgU2VsZi1TaWduZWQwggGiMA0GCSqGSIb3DQEB
# AQUAA4IBjwAwggGKAoIBgQC4A+QoBzUXkXXMoVrptgMss1BNRwJhNcYop9CKHvJY
# QnBLkhSI10Z7EBCZsDSAfICechL0e7Lrwaz8/sTRQeITCKMRzxFe9Oq1CxZfRUh0
# U1T/m8+9q/OR0C6hCSZ9LvpiZExBSmQsQlXyl8smfFK2+gecLOQUPFD7gcpM03gv
# 6OkX/bLpBQZs52K3RnH+YKje0L6W985qxn1M5nDmC4rc2U90k4evzMMPOjTX7jZA
# PHOT3g6ByPWI2SNowO1ptXheS4KGjbx3IH+4+r4UwIPc32hauiAfjXr63inQdkII
# 7tYVI5GBiJB20Gzujm5KuHU9qVXMvAAk7WR9DBGdH4Pq5Or3WD58KV2Mazx0SWhV
# A4ikEEENTbaWIaFEYgWR2PAtPv7rt/p5ZK05fP7Nt/TfSHzBFQsKS4wFchiWQTVj
# kdAPuzsipnwiJyOSmQ7FppnuuhUxEq9ZkOigDLett9ZoY5oNcASOnpCWnxnWx/aq
# xDuJOnKBOGRly1KFUQ+OABUCAwEAAaNGMEQwDgYDVR0PAQH/BAQDAgeAMBMGA1Ud
# JQQMMAoGCCsGAQUFBwMDMB0GA1UdDgQWBBQkjQccxcT1k6xhYBW0XHlelX6nFjAN
# BgkqhkiG9w0BAQsFAAOCAYEAk3bN0vTJBIFnyLm4zxarRLfr6uEl9Y2Xk4P16AxG
# DDLN+Zd7T+oblgAIz4/0EHPJ3DsonLsjOnZBOp5iJr1nSxBy9Cs6K1T6k2mtSr93
# mOT2MSNDlLOFhk37U46yFDJHfX4rQLTmltOoUpeU7V7Cr5EnWJ4xbdmexZUx5vz+
# qeqqe86VxT00Npb5OXINvs8+gH85J+x4HWmrTDzruME1JLkX388g3AQvVd5Xf0YY
# 2InRPQ7Y0jrzccH6OSz14DHSnzN5pKzVzvv9aFDuZ+gCkbC8ZIr890I8WXxbYskX
# 8bTTP0Sa8Jhw22OCOwzDhFxxqivhbqHRybgQ6KdSoDxS51WHp3saGlWfwmFyWkIe
# L5eEpdz8r2vpTbaJVZnVT/SxpYobgZIn3zbss0JFiltcgguIoc+fNbMEUoqnEARQ
# dD4+fIPF32CUclDI6JpugYJLSuvJt6gy4k78A1jQaYTbdZ6Twt+Pup+3ocnWmeyV
# umYxx47CZmI93XUw5yflFPRUMYICgDCCAnwCAQEwTjA6MTgwNgYDVQQDDC9TbWFy
# dE0zNjUgT3JjaGVzdHJhdG9yIENvZGUgU2lnbmluZyBTZWxmLVNpZ25lZAIQcbtB
# Ir5QhbVGyT33v1WuajANBglghkgBZQMEAgEFAKCBhDAYBgorBgEEAYI3AgEMMQow
# CKACgAChAoAAMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisGAQQBgjcC
# AQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3DQEJBDEiBCAAvMLsb6lJwbK1kes8
# fIAcrZf5muExau4o9mievYKA3TANBgkqhkiG9w0BAQEFAASCAYBjmNqF2BZSuU7i
# uFxiYD5FDNDyuIvPYEVqelleKom5R2vSCvSb/wVzZuhz2VlVixbkrxLwPsdOzlOV
# aRbp/n9JcvN06lLagsZPghRadV5bgn6nFPfWaNQGyAfzuyqZ1ORAk2E8w4vnxHC8
# iLueIsxy/HCiqBaHDpqz8IJWdsnqPe7t8UNRw5B7h/yPvhYqsk5rFO0V8dEg2XT3
# NItRfwh0rF2p/sQwkgiAzbuQYq1B3WTqwykDEsmvE7hN5tRUzZ2BTQg0vQW92V9j
# XROXHr+uJI/qoZWHSUI3Es+NzrCi5Q6hJ0FqOWoyTDrP6nIofcRjSu2pe7rXi/m+
# vxFgc+UMI29GmrNwIhGKoBzT12UOhiJaAp+/4TmE5uWvvXMaZwMvL8PXZSJgMA9Z
# 6zAoMRA06jFVknChnvLam/xGPKMGZmzT9IZjJBV6Y70iAQGku6wfmsQhy6hGbBol
# nERfKvzmSTsEJSiBeZRweuMgJLeRsxWfOBFF3Bv0Iqm/rI5I9Ws=
# SIG # End signature block
