<#
.SYNOPSIS
    Compares SharePoint 2019 and SharePoint Online file inventory CSV exports.

.DESCRIPTION
    Compares two CSV files generated by SmartM365-SharePointSource-FileInventory.ps1 and
    SmartM365-SharePointTarget-FileInventory.ps1. The comparison is based on a normalized
    ServerRelativeUrl, with optional path prefixes removed from each side.

    Output files:
    - MissingInTarget.csv: files present in source but missing in target
    - ExtraInTarget.csv: files present in target but missing in source
    - DifferentSize.csv: files present in both but with different SizeBytes
    - Summary.csv: high-level counts

.EXAMPLE
    .\SmartM365-SharePointSourceTarget-FileInventoriesCompare.ps1 `
      -SourceCsv ".\Scans\Source\SP2019-FileInventory-Source-20260529-184257.csv" `
      -TargetCsv ".\Scans\Target\SPO-FileInventory-Target-20260529-194037.csv" `
      -TargetPrefixToRemove "/sites/TargetSite" `
      -ComparisonName "Migration"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$SourceCsv,

    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$TargetCsv,

    [string[]]$SourcePrefixToRemove = @(),

    [string[]]$TargetPrefixToRemove = @(),

    [ValidateNotNullOrEmpty()]
    [string]$OutputDirectory,

    [ValidateNotNullOrEmpty()]
    [string]$LogPath,

    [ValidateNotNullOrEmpty()]
    [string]$ComparisonName = 'SharePointInventoryComparison',

    [long]$SizeToleranceBytes = 10240
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

function Get-ConsoleTimestamp {
    return (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
}

function Write-Host {
    param(
        [Parameter(Position = 0, ValueFromRemainingArguments = $true)]
        [object[]]$Object,

        [ConsoleColor]$ForegroundColor,

        [switch]$NoNewline
    )

    $message = if ($Object) { ($Object -join ' ') } else { '' }
    $line = if ($message -match '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} ') { $message } else { "{0} {1}" -f (Get-ConsoleTimestamp), $message }
    $parameters = @{ Object = $line }
    if ($PSBoundParameters.ContainsKey('ForegroundColor')) { $parameters.ForegroundColor = $ForegroundColor }
    if ($NoNewline) { $parameters.NoNewline = $true }
    Microsoft.PowerShell.Utility\Write-Host @parameters
}

function Add-TimestampToLogFile {
    param([string]$Path)

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        return
    }

    $timestampPattern = '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} '
    $content = Get-Content -LiteralPath $Path
    $updated = foreach ($line in $content) {
        if ($line -match $timestampPattern -or [string]::IsNullOrWhiteSpace($line)) {
            $line
        }
        else {
            "{0} {1}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $line
        }
    }

    Set-Content -LiteralPath $Path -Value $updated -Encoding UTF8 -WhatIf:$false
}

function Stop-TimestampedTranscript {
    param([string]$Path)

    try {
        Stop-Transcript | Out-Null
    }
    catch {
        return
    }

    Add-TimestampToLogFile -Path $Path
}

function Write-Info {
    param(
        [string]$Message,
        [ConsoleColor]$Color = [ConsoleColor]::Gray
    )

    Write-Host $Message -ForegroundColor $Color
}

function Resolve-InputPath {
    param(
        [string]$Path
    )

    $resolved = Resolve-Path -LiteralPath $Path -ErrorAction Stop
    return $resolved.Path
}

function ConvertTo-NormalizedPath {
    param(
        [string]$Path,
        [string[]]$PrefixesToRemove
    )

    if ([string]::IsNullOrWhiteSpace($Path)) {
        return $null
    }

    $normalized = [System.Uri]::UnescapeDataString($Path.Trim())
    $normalized = $normalized -replace '\\', '/'
    $normalized = $normalized -replace '[?#].*$', ''

    if ($normalized -match '^https?://') {
        try {
            $normalized = ([System.Uri]$normalized).AbsolutePath
        }
        catch {
            return $null
        }
    }

    if (-not $normalized.StartsWith('/')) {
        $normalized = "/$normalized"
    }

    $normalized = $normalized.TrimEnd('/')
    if ([string]::IsNullOrWhiteSpace($normalized)) {
        $normalized = '/'
    }

    foreach ($prefix in $PrefixesToRemove) {
        if ([string]::IsNullOrWhiteSpace($prefix)) {
            continue
        }

        $cleanPrefix = [System.Uri]::UnescapeDataString($prefix.Trim())
        if ($cleanPrefix -match '^https?://') {
            $cleanPrefix = ([System.Uri]$cleanPrefix).AbsolutePath
        }

        if (-not $cleanPrefix.StartsWith('/')) {
            $cleanPrefix = "/$cleanPrefix"
        }

        $cleanPrefix = $cleanPrefix.TrimEnd('/')
        if ([string]::IsNullOrWhiteSpace($cleanPrefix)) {
            continue
        }

        if ($normalized.Equals($cleanPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
            $normalized = '/'
            break
        }

        if ($normalized.StartsWith("$cleanPrefix/", [System.StringComparison]::OrdinalIgnoreCase)) {
            $normalized = $normalized.Substring($cleanPrefix.Length)
            break
        }
    }

    if (-not $normalized.StartsWith('/')) {
        $normalized = "/$normalized"
    }

    $normalized = $normalized -replace '/+', '/'
    return $normalized.ToLowerInvariant()
}

function Get-InventoryKey {
    param(
        $Row,
        [string[]]$PrefixesToRemove
    )

    $path = $Row.ServerRelativeUrl
    if ([string]::IsNullOrWhiteSpace($path)) {
        $path = $Row.FileUrl
    }

    return ConvertTo-NormalizedPath -Path $path -PrefixesToRemove $PrefixesToRemove
}

function ConvertTo-InventoryRecord {
    param(
        $Row,
        [string]$Key
    )

    [pscustomobject]@{
        Key               = $Key
        SiteCollectionUrl = $Row.SiteCollectionUrl
        WebUrl            = $Row.WebUrl
        WebTitle          = $Row.WebTitle
        LibraryTitle      = $Row.LibraryTitle
        FileName          = $Row.FileName
        ServerRelativeUrl = $Row.ServerRelativeUrl
        FileUrl           = $Row.FileUrl
        SizeBytes         = $Row.SizeBytes
        Modified          = $Row.Modified
        ModifiedBy        = $Row.ModifiedBy
    }
}

function Export-Row {
    param(
        [Parameter(Mandatory = $true)]
        $Row,

        [Parameter(Mandatory = $true)]
        [string]$Path,

        [ref]$Created
    )

    if ($Created.Value) {
        $Row | Export-Csv -Delimiter ';' -LiteralPath $Path -NoTypeInformation -Encoding UTF8 -Append
    }
    else {
        $Row | Export-Csv -Delimiter ';' -LiteralPath $Path -NoTypeInformation -Encoding UTF8
        $Created.Value = $true
    }
}

function Get-CsvDelimiter {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    $firstLine = Get-Content -LiteralPath $Path -TotalCount 1
    if (([regex]::Matches($firstLine, ';')).Count -gt ([regex]::Matches($firstLine, ',')).Count) {
        return ';'
    }

    return ','
}

function Import-CsvAutoDelimiter {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    Import-Csv -LiteralPath $Path -Delimiter (Get-CsvDelimiter -Path $Path)
}

function ConvertTo-CsvField {
    param(
        $Value
    )

    if ($null -eq $Value) {
        return '""'
    }

    $text = [string]$Value
    $text = $text.Replace('"', '""')
    return '"' + $text + '"'
}

function Write-CsvRecord {
    param(
        [System.IO.StreamWriter]$Writer,
        [string[]]$Columns,
        $Row
    )

    $values = foreach ($column in $Columns) {
        ConvertTo-CsvField -Value $Row.$column
    }

    $Writer.WriteLine(($values -join ','))
}

function Get-LongValue {
    param(
        $Value
    )

    if ($null -eq $Value -or [string]::IsNullOrWhiteSpace([string]$Value)) {
        return $null
    }

    return [long]$Value
}

$SourceCsv = Resolve-InputPath -Path $SourceCsv
$TargetCsv = Resolve-InputPath -Path $TargetCsv

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $safeName = ($ComparisonName -replace '[\\/:*?"<>|]+', '-').Trim()
    if ([string]::IsNullOrWhiteSpace($safeName)) {
        $safeName = 'SharePointInventoryComparison'
    }

    $scriptDirectory = if ($PSScriptRoot) { $PSScriptRoot } else { (Get-Location).Path }
    $projectDirectory = Split-Path -Path (Split-Path -Path $scriptDirectory -Parent) -Parent
    $OutputDirectory = Join-Path -Path $projectDirectory -ChildPath (Join-Path -Path 'ComparisonResults' -ChildPath ("{0}-{1:yyyyMMdd-HHmmss}" -f $safeName, (Get-Date)))
}

New-Item -Path $OutputDirectory -ItemType Directory -Force | Out-Null

if ([string]::IsNullOrWhiteSpace($LogPath)) {
    $safeLogName = ($ComparisonName -replace '[\\/:*?"<>|]+', '-').Trim()
    if ([string]::IsNullOrWhiteSpace($safeLogName)) {
        $safeLogName = 'SharePointInventoryComparison'
    }
    $LogPath = Join-Path -Path (Join-Path -Path $OutputDirectory -ChildPath 'logs') -ChildPath ("{0}-{1:yyyyMMdd-HHmmss}-Run.log" -f $safeLogName, (Get-Date))
}

$logDirectory = Split-Path -Path $LogPath -Parent
if ($logDirectory -and -not (Test-Path -LiteralPath $logDirectory -PathType Container)) {
    New-Item -ItemType Directory -Path $logDirectory -Force | Out-Null
}

$script:TranscriptStarted = $false
trap {
    if ($script:TranscriptStarted) {
        Stop-TimestampedTranscript -Path $LogPath
    }
    throw $_
}

Start-Transcript -Path $LogPath -Force -WhatIf:$false | Out-Null
$script:TranscriptStarted = $true

$missingPath = Join-Path -Path $OutputDirectory -ChildPath 'MissingInTarget.csv'
$extraPath = Join-Path -Path $OutputDirectory -ChildPath 'ExtraInTarget.csv'
$differentSizePath = Join-Path -Path $OutputDirectory -ChildPath 'DifferentSize.csv'
$summaryPath = Join-Path -Path $OutputDirectory -ChildPath 'Summary.csv'

$inventoryColumns = @(
    'Key',
    'SiteCollectionUrl',
    'WebUrl',
    'WebTitle',
    'LibraryTitle',
    'FileName',
    'ServerRelativeUrl',
    'FileUrl',
    'SizeBytes',
    'Modified',
    'ModifiedBy'
)

$differentSizeColumns = @(
    'Key',
    'SourceSizeBytes',
    'TargetSizeBytes',
    'DeltaBytes',
    'SourceWebUrl',
    'TargetWebUrl',
    'SourceLibraryTitle',
    'TargetLibraryTitle',
    'SourceServerRelativeUrl',
    'TargetServerRelativeUrl',
    'SourceModified',
    'TargetModified'
)

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$missingWriter = New-Object System.IO.StreamWriter($missingPath, $false, $utf8NoBom)
$extraWriter = New-Object System.IO.StreamWriter($extraPath, $false, $utf8NoBom)
$differentSizeWriter = New-Object System.IO.StreamWriter($differentSizePath, $false, $utf8NoBom)

$missingWriter.WriteLine(($inventoryColumns | ForEach-Object { ConvertTo-CsvField -Value $_ }) -join ',')
$extraWriter.WriteLine(($inventoryColumns | ForEach-Object { ConvertTo-CsvField -Value $_ }) -join ',')
$differentSizeWriter.WriteLine(($differentSizeColumns | ForEach-Object { ConvertTo-CsvField -Value $_ }) -join ',')

Write-Info -Color Cyan -Message "Source CSV: $SourceCsv"
Write-Info -Color Cyan -Message "Target CSV: $TargetCsv"
Write-Info -Color Cyan -Message "Output directory: $OutputDirectory"
Write-Info -Color Cyan -Message "Run log: $LogPath"

$sourceIndex = @{}
$sourceTotalRows = 0
$sourceUniqueKeys = 0
$sourceDuplicateKeys = 0

Write-Info -Color Yellow -Message 'Indexing source inventory...'
Import-CsvAutoDelimiter -Path $SourceCsv | ForEach-Object {
    $sourceTotalRows++
    $key = Get-InventoryKey -Row $_ -PrefixesToRemove $SourcePrefixToRemove
    if ([string]::IsNullOrWhiteSpace($key)) {
        return
    }

    if ($sourceIndex.ContainsKey($key)) {
        $sourceDuplicateKeys++
        return
    }

    $sourceIndex[$key] = ConvertTo-InventoryRecord -Row $_ -Key $key
    $sourceUniqueKeys++
}

Write-Info -Color Green -Message ("Source rows: {0}; unique keys: {1}; duplicate keys ignored: {2}" -f $sourceTotalRows, $sourceUniqueKeys, $sourceDuplicateKeys)

$targetSeenKeys = New-Object 'System.Collections.Generic.HashSet[string]' ([System.StringComparer]::OrdinalIgnoreCase)
$targetTotalRows = 0
$targetUniqueKeys = 0
$targetDuplicateKeys = 0
$matched = 0
$extra = 0
$differentSize = 0

Write-Info -Color Yellow -Message 'Comparing target inventory...'
Import-CsvAutoDelimiter -Path $TargetCsv | ForEach-Object {
    $targetTotalRows++
    $key = Get-InventoryKey -Row $_ -PrefixesToRemove $TargetPrefixToRemove
    if ([string]::IsNullOrWhiteSpace($key)) {
        return
    }

    if (-not $targetSeenKeys.Add($key)) {
        $targetDuplicateKeys++
        return
    }

    $targetUniqueKeys++
    $targetRecord = ConvertTo-InventoryRecord -Row $_ -Key $key

    if (-not $sourceIndex.ContainsKey($key)) {
        $extra++
        Write-CsvRecord -Writer $extraWriter -Columns $inventoryColumns -Row $targetRecord
        return
    }

    $matched++
    $sourceRecord = $sourceIndex[$key]
    $sourceSize = Get-LongValue -Value $sourceRecord.SizeBytes
    $targetSize = Get-LongValue -Value $targetRecord.SizeBytes

    if ($null -ne $sourceSize -and $null -ne $targetSize -and [math]::Abs($sourceSize - $targetSize) -gt $SizeToleranceBytes) {
        $differentSize++
        Write-CsvRecord -Writer $differentSizeWriter -Columns $differentSizeColumns -Row ([pscustomobject]@{
            Key                     = $key
            SourceSizeBytes          = $sourceSize
            TargetSizeBytes          = $targetSize
            DeltaBytes               = $targetSize - $sourceSize
            SourceWebUrl             = $sourceRecord.WebUrl
            TargetWebUrl             = $targetRecord.WebUrl
            SourceLibraryTitle       = $sourceRecord.LibraryTitle
            TargetLibraryTitle       = $targetRecord.LibraryTitle
            SourceServerRelativeUrl  = $sourceRecord.ServerRelativeUrl
            TargetServerRelativeUrl  = $targetRecord.ServerRelativeUrl
            SourceModified           = $sourceRecord.Modified
            TargetModified           = $targetRecord.Modified
        })
    }
}

$missing = 0

Write-Info -Color Yellow -Message 'Finding source files missing from target...'
foreach ($entry in $sourceIndex.GetEnumerator()) {
    if (-not $targetSeenKeys.Contains($entry.Key)) {
        $missing++
        Write-CsvRecord -Writer $missingWriter -Columns $inventoryColumns -Row $entry.Value
    }
}

$summary = [pscustomobject]@{
    ComparisonName             = $ComparisonName
    SourceCsv                  = $SourceCsv
    TargetCsv                  = $TargetCsv
    SourceRows                 = $sourceTotalRows
    SourceUniqueKeys           = $sourceUniqueKeys
    SourceDuplicateKeysIgnored = $sourceDuplicateKeys
    TargetRows                 = $targetTotalRows
    TargetUniqueKeys           = $targetUniqueKeys
    TargetDuplicateKeysIgnored = $targetDuplicateKeys
    MatchedKeys                = $matched
    MissingInTarget            = $missing
    ExtraInTarget              = $extra
    DifferentSize              = $differentSize
    SizeToleranceBytes         = $SizeToleranceBytes
    OutputDirectory            = $OutputDirectory
}

$missingWriter.Close()
$extraWriter.Close()
$differentSizeWriter.Close()

$summary | Export-Csv -Delimiter ';' -LiteralPath $summaryPath -NoTypeInformation -Encoding UTF8

Write-Info -Color Green -Message 'Comparison completed.'
Write-Info -Color Green -Message ("Matched: {0}; Missing in target: {1}; Extra in target: {2}; Different size: {3}" -f $matched, $missing, $extra, $differentSize)
Write-Info -Color Cyan -Message "Summary: $summaryPath"

if ($script:TranscriptStarted) {
    Stop-TimestampedTranscript -Path $LogPath
    $script:TranscriptStarted = $false
}

# SIG # Begin signature block
# MIIeYwYJKoZIhvcNAQcCoIIeVDCCHlACAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBe+70PcnEI+fgp
# kVa03y8mhxgPoUtiOacH9s5GqpFJNKCCF/swggS9MIIDJaADAgECAhAebu87xzjh
# s0Q4yPEDH+JoMA0GCSqGSIb3DQEBCwUAME4xHjAcBgNVBAMMFXdvcmtwbGFjZWNs
# b3VkaHViLmNvbTEsMCoGCSqGSIb3DQEJARYdY29udGFjdEB3b3JrcGxhY2VjbG91
# ZGh1Yi5jb20wHhcNMjYwNzEzMDgyMjM1WhcNMjkwNzEzMDgzMjI5WjBOMR4wHAYD
# VQQDDBV3b3JrcGxhY2VjbG91ZGh1Yi5jb20xLDAqBgkqhkiG9w0BCQEWHWNvbnRh
# Y3RAd29ya3BsYWNlY2xvdWRodWIuY29tMIIBojANBgkqhkiG9w0BAQEFAAOCAY8A
# MIIBigKCAYEAse6XztERSyHn9DVqj8Rdv0qjc5owqvgAIGaYxBmfiQuoM48Fo4Xt
# 1ovi9brLUtf55G4XgthNPCoanxfCRRg30IVRxaDfdPXJzYmgsM5tXlsuNU49lE7E
# PJk3+jEOgSCt8NKzmVPKpNRG0NmK0a8wm12cceYZOZlSYE0+ZtT6wy5PQQjMUqIx
# XnGjt4H0nfgZZa7D4FyARKOVg/Xr9sUq5jIn3zszvg4jjeb4b0DKJtfbHukhWc2Y
# oVFgswxVBXCWIaBnfF/cjqMfK/CaToT2trVb4hG4qcQ31s1nR4keoRaOw/vyd6ap
# rEtCsT22N/Jx0dz7fIo1tVyvIaVcHdN9LW3chn0en0OKZ6Ke1OH9wf2prl4KA6Ww
# VzrAZrOlXTAItdK7D9kKO/HeJd4PZvO53oy1LdmMGLSz3OLB9e5q7yo8rfqi5Ka9
# KzM2CrSzz1yphn/H90wz7Q2pm4FIlWdcj86A/0kmhYg+5Wqqbg1drrPXu4nEBwWN
# /dzoGtKZKHTdAgMBAAGjgZYwgZMwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoG
# CCsGAQUFBwMDMD8GA1UdEQQ4MDaBHWNvbnRhY3RAd29ya3BsYWNlY2xvdWRodWIu
# Y29tghV3b3JrcGxhY2VjbG91ZGh1Yi5jb20wDAYDVR0TAQH/BAIwADAdBgNVHQ4E
# FgQUXIOOADQM78XfPAncirgCECedg9gwDQYJKoZIhvcNAQELBQADggGBADhZUB2R
# 5J/Jw030xodhEWeCQ0vnJRaiEsjOxuArQREKH3lCrQ3UsUVl292d6LnQUSTH/jF7
# rovEZ+JN2GQ/LCrXRaCuwCEGZKzlSEbtYWhfwDyj6GpIPq8Y4SeXyjdq4/rrI1bm
# iTK4Sq7EoBlGJuX6l2nfvx1tTioSr11FoDfllJR7EYawRj9hBFJ0gG0b2SuYZMgW
# gaDKefcnJDmOwcRNAZUII0ss8EeyANukWSkNN5ILZ+iKDpQgZxgDLPTiRguCyx45
# PI5wrVTjV/pR7IrtSIfq8UladlrSZJyyDn3NV2ATvIZ6wNxbTmPFcE0uMg/EYzwd
# Tek+CgXL3TxUKeldJM4YDWPimNBRhOPXzBDiOQIj6WNswt/KM1oDLnA00CNtciPN
# dn+dXlneMvTEUah9wyt8o8tkLpoBw+KN+Bq/K0O1qPtS7umi70l45pPiej+mwbwq
# ztcaoVD7a8ggHP1Vdp/rnafM4GtyCAE6b7U9Yzgvp1/a1kh7XffmqVhRRjCCBY0w
# ggR1oAMCAQICEA6bGI750C3n79tQ4ghAGFowDQYJKoZIhvcNAQEMBQAwZTELMAkG
# A1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3LmRp
# Z2ljZXJ0LmNvbTEkMCIGA1UEAxMbRGlnaUNlcnQgQXNzdXJlZCBJRCBSb290IENB
# MB4XDTIyMDgwMTAwMDAwMFoXDTMxMTEwOTIzNTk1OVowYjELMAkGA1UEBhMCVVMx
# FTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNv
# bTEhMB8GA1UEAxMYRGlnaUNlcnQgVHJ1c3RlZCBSb290IEc0MIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAv+aQc2jeu+RdSjwwIjBpM+zCpyUuySE98orY
# WcLhKac9WKt2ms2uexuEDcQwH/MbpDgW61bGl20dq7J58soR0uRf1gU8Ug9SH8ae
# FaV+vp+pVxZZVXKvaJNwwrK6dZlqczKU0RBEEC7fgvMHhOZ0O21x4i0MG+4g1ckg
# HWMpLc7sXk7Ik/ghYZs06wXGXuxbGrzryc/NrDRAX7F6Zu53yEioZldXn1RYjgwr
# t0+nMNlW7sp7XeOtyU9e5TXnMcvak17cjo+A2raRmECQecN4x7axxLVqGDgDEI3Y
# 1DekLgV9iPWCPhCRcKtVgkEy19sEcypukQF8IUzUvK4bA3VdeGbZOjFEmjNAvwjX
# WkmkwuapoGfdpCe8oU85tRFYF/ckXEaPZPfBaYh2mHY9WV1CdoeJl2l6SPDgohIb
# Zpp0yt5LHucOY67m1O+SkjqePdwA5EUlibaaRBkrfsCUtNJhbesz2cXfSwQAzH0c
# lcOP9yGyshG3u3/y1YxwLEFgqrFjGESVGnZifvaAsPvoZKYz0YkH4b235kOkGLim
# dwHhD5QMIR2yVCkliWzlDlJRR3S+Jqy2QXXeeqxfjT/JvNNBERJb5RBQ6zHFynIW
# IgnffEx1P2PsIV/EIFFrb7GrhotPwtZFX50g/KEexcCPorF+CiaZ9eRpL5gdLfXZ
# qbId5RsCAwEAAaOCATowggE2MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFOzX
# 44LScV1kTN8uZz/nupiuHA9PMB8GA1UdIwQYMBaAFEXroq/0ksuCMS1Ri6enIZ3z
# bcgPMA4GA1UdDwEB/wQEAwIBhjB5BggrBgEFBQcBAQRtMGswJAYIKwYBBQUHMAGG
# GGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBDBggrBgEFBQcwAoY3aHR0cDovL2Nh
# Y2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0QXNzdXJlZElEUm9vdENBLmNydDBF
# BgNVHR8EPjA8MDqgOKA2hjRodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNl
# cnRBc3N1cmVkSURSb290Q0EuY3JsMBEGA1UdIAQKMAgwBgYEVR0gADANBgkqhkiG
# 9w0BAQwFAAOCAQEAcKC/Q1xV5zhfoKN0Gz22Ftf3v1cHvZqsoYcs7IVeqRq7IviH
# GmlUIu2kiHdtvRoU9BNKei8ttzjv9P+Aufih9/Jy3iS8UgPITtAq3votVs/59Pes
# MHqai7Je1M/RQ0SbQyHrlnKhSLSZy51PpwYDE3cnRNTnf+hZqPC/Lwum6fI0POz3
# A8eHqNJMQBk1RmppVLC4oVaO7KTVPeix3P0c2PR3WlxUjG/voVA9/HYJaISfb8rb
# II01YBwCA8sgsKxYoA5AY8WYIsGyWfVVa88nq2x2zm8jLfR+cWojayL/ErhULSd+
# 2DrZ8LaHlv1b0VysGMNNn3O3AamfV6peKOK5lDCCBrQwggScoAMCAQICEA3HrFcF
# /yGZLkBDIgw6SYYwDQYJKoZIhvcNAQELBQAwYjELMAkGA1UEBhMCVVMxFTATBgNV
# BAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTEhMB8G
# A1UEAxMYRGlnaUNlcnQgVHJ1c3RlZCBSb290IEc0MB4XDTI1MDUwNzAwMDAwMFoX
# DTM4MDExNDIzNTk1OVowaTELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0
# LCBJbmMuMUEwPwYDVQQDEzhEaWdpQ2VydCBUcnVzdGVkIEc0IFRpbWVTdGFtcGlu
# ZyBSU0E0MDk2IFNIQTI1NiAyMDI1IENBMTCCAiIwDQYJKoZIhvcNAQEBBQADggIP
# ADCCAgoCggIBALR4MdMKmEFyvjxGwBysddujRmh0tFEXnU2tjQ2UtZmWgyxU7UNq
# EY81FzJsQqr5G7A6c+Gh/qm8Xi4aPCOo2N8S9SLrC6Kbltqn7SWCWgzbNfiR+2fk
# HUiljNOqnIVD/gG3SYDEAd4dg2dDGpeZGKe+42DFUF0mR/vtLa4+gKPsYfwEu7EE
# bkC9+0F2w4QJLVSTEG8yAR2CQWIM1iI5PHg62IVwxKSpO0XaF9DPfNBKS7Zazch8
# NF5vp7eaZ2CVNxpqumzTCNSOxm+SAWSuIr21Qomb+zzQWKhxKTVVgtmUPAW35xUU
# FREmDrMxSNlr/NsJyUXzdtFUUt4aS4CEeIY8y9IaaGBpPNXKFifinT7zL2gdFpBP
# 9qh8SdLnEut/GcalNeJQ55IuwnKCgs+nrpuQNfVmUB5KlCX3ZA4x5HHKS+rqBvKW
# xdCyQEEGcbLe1b8Aw4wJkhU1JrPsFfxW1gaou30yZ46t4Y9F20HHfIY4/6vHespY
# MQmUiote8ladjS/nJ0+k6MvqzfpzPDOy5y6gqztiT96Fv/9bH7mQyogxG9QEPHrP
# V6/7umw052AkyiLA6tQbZl1KhBtTasySkuJDpsZGKdlsjg4u70EwgWbVRSX1Wd4+
# zoFpp4Ra+MlKM2baoD6x0VR4RjSpWM8o5a6D8bpfm4CLKczsG7ZrIGNTAgMBAAGj
# ggFdMIIBWTASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBTvb1NK6eQGfHrK
# 4pBW9i/USezLTjAfBgNVHSMEGDAWgBTs1+OC0nFdZEzfLmc/57qYrhwPTzAOBgNV
# HQ8BAf8EBAMCAYYwEwYDVR0lBAwwCgYIKwYBBQUHAwgwdwYIKwYBBQUHAQEEazBp
# MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wQQYIKwYBBQUH
# MAKGNWh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRS
# b290RzQuY3J0MEMGA1UdHwQ8MDowOKA2oDSGMmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0
# LmNvbS9EaWdpQ2VydFRydXN0ZWRSb290RzQuY3JsMCAGA1UdIAQZMBcwCAYGZ4EM
# AQQCMAsGCWCGSAGG/WwHATANBgkqhkiG9w0BAQsFAAOCAgEAF877FoAc/gc9EXZx
# ML2+C8i1NKZ/zdCHxYgaMH9Pw5tcBnPw6O6FTGNpoV2V4wzSUGvI9NAzaoQk97fr
# PBtIj+ZLzdp+yXdhOP4hCFATuNT+ReOPK0mCefSG+tXqGpYZ3essBS3q8nL2UwM+
# NMvEuBd/2vmdYxDCvwzJv2sRUoKEfJ+nN57mQfQXwcAEGCvRR2qKtntujB71WPYA
# gwPyWLKu6RnaID/B0ba2H3LUiwDRAXx1Neq9ydOal95CHfmTnM4I+ZI2rVQfjXQA
# 1WSjjf4J2a7jLzWGNqNX+DF0SQzHU0pTi4dBwp9nEC8EAqoxW6q17r0z0noDjs6+
# BFo+z7bKSBwZXTRNivYuve3L2oiKNqetRHdqfMTCW/NmKLJ9M+MtucVGyOxiDf06
# VXxyKkOirv6o02OoXN4bFzK0vlNMsvhlqgF2puE6FndlENSmE+9JGYxOGLS/D284
# NHNboDGcmWXfwXRy4kbu4QFhOm0xJuF2EZAOk5eCkhSxZON3rGlHqhpB/8MluDez
# ooIs8CVnrpHMiD2wL40mm53+/j7tFaxYKIqL0Q4ssd8xHZnIn/7GELH3IdvG2XlM
# 9q7WP/UwgOkw/HQtyRN62JK4S1C8uw3PdBunvAZapsiI5YKdvlarEvf8EA+8hcpS
# M9LHJmyrxaFtoza2zNaQ9k+5t1wwggbtMIIE1aADAgECAhAKgO8YS43xBYLRxHan
# lXRoMA0GCSqGSIb3DQEBCwUAMGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdp
# Q2VydCwgSW5jLjFBMD8GA1UEAxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBUaW1lU3Rh
# bXBpbmcgUlNBNDA5NiBTSEEyNTYgMjAyNSBDQTEwHhcNMjUwNjA0MDAwMDAwWhcN
# MzYwOTAzMjM1OTU5WjBjMQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQs
# IEluYy4xOzA5BgNVBAMTMkRpZ2lDZXJ0IFNIQTI1NiBSU0E0MDk2IFRpbWVzdGFt
# cCBSZXNwb25kZXIgMjAyNSAxMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
# AgEA0EasLRLGntDqrmBWsytXum9R/4ZwCgHfyjfMGUIwYzKomd8U1nH7C8Dr0cVM
# F3BsfAFI54um8+dnxk36+jx0Tb+k+87H9WPxNyFPJIDZHhAqlUPt281mHrBbZHqR
# K71Em3/hCGC5KyyneqiZ7syvFXJ9A72wzHpkBaMUNg7MOLxI6E9RaUueHTQKWXym
# OtRwJXcrcTTPPT2V1D/+cFllESviH8YjoPFvZSjKs3SKO1QNUdFd2adw44wDcKgH
# +JRJE5Qg0NP3yiSyi5MxgU6cehGHr7zou1znOM8odbkqoK+lJ25LCHBSai25CFyD
# 23DZgPfDrJJJK77epTwMP6eKA0kWa3osAe8fcpK40uhktzUd/Yk0xUvhDU6lvJuk
# x7jphx40DQt82yepyekl4i0r8OEps/FNO4ahfvAk12hE5FVs9HVVWcO5J4dVmVzi
# x4A77p3awLbr89A90/nWGjXMGn7FQhmSlIUDy9Z2hSgctaepZTd0ILIUbWuhKuAe
# NIeWrzHKYueMJtItnj2Q+aTyLLKLM0MheP/9w6CtjuuVHJOVoIJ/DtpJRE7Ce7vM
# RHoRon4CWIvuiNN1Lk9Y+xZ66lazs2kKFSTnnkrT3pXWETTJkhd76CIDBbTRofOs
# NyEhzZtCGmnQigpFHti58CSmvEyJcAlDVcKacJ+A9/z7eacCAwEAAaOCAZUwggGR
# MAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFOQ7/PIx7f391/ORcWMZUEPPYYzoMB8G
# A1UdIwQYMBaAFO9vU0rp5AZ8esrikFb2L9RJ7MtOMA4GA1UdDwEB/wQEAwIHgDAW
# BgNVHSUBAf8EDDAKBggrBgEFBQcDCDCBlQYIKwYBBQUHAQEEgYgwgYUwJAYIKwYB
# BQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBdBggrBgEFBQcwAoZRaHR0
# cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZEc0VGltZVN0
# YW1waW5nUlNBNDA5NlNIQTI1NjIwMjVDQTEuY3J0MF8GA1UdHwRYMFYwVKBSoFCG
# Tmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRHNFRpbWVT
# dGFtcGluZ1JTQTQwOTZTSEEyNTYyMDI1Q0ExLmNybDAgBgNVHSAEGTAXMAgGBmeB
# DAEEAjALBglghkgBhv1sBwEwDQYJKoZIhvcNAQELBQADggIBAGUqrfEcJwS5rmBB
# 7NEIRJ5jQHIh+OT2Ik/bNYulCrVvhREafBYF0RkP2AGr181o2YWPoSHz9iZEN/FP
# sLSTwVQWo2H62yGBvg7ouCODwrx6ULj6hYKqdT8wv2UV+Kbz/3ImZlJ7YXwBD9R0
# oU62PtgxOao872bOySCILdBghQ/ZLcdC8cbUUO75ZSpbh1oipOhcUT8lD8QAGB9l
# ctZTTOJM3pHfKBAEcxQFoHlt2s9sXoxFizTeHihsQyfFg5fxUFEp7W42fNBVN4ue
# LaceRf9Cq9ec1v5iQMWTFQa0xNqItH3CPFTG7aEQJmmrJTV3Qhtfparz+BW60OiM
# EgV5GWoBy4RVPRwqxv7Mk0Sy4QHs7v9y69NBqycz0BZwhB9WOfOu/CIJnzkQTwtS
# SpGGhLdjnQ4eBpjtP+XB3pQCtv4E5UCSDag6+iX8MmB10nfldPF9SVD7weCC3yXZ
# i/uuhqdwkgVxuiMFzGVFwYbQsiGnoa9F5AaAyBjFBtXVLcKtapnMG3VH3EmAp/js
# J3FVF3+d1SVDTmjFjLbNFZUWMXuZyvgLfgyPehwJVxwC+UpX2MSey2ueIu9THFVk
# T+um1vshETaWyQo8gmBto/m3acaP9QsuLj3FNwFlTxq25+T4QwX9xa6ILs84ZPvm
# povq90K8eWyG2N01c4IhSOxqt81nMYIFvjCCBboCAQEwYjBOMR4wHAYDVQQDDBV3
# b3JrcGxhY2VjbG91ZGh1Yi5jb20xLDAqBgkqhkiG9w0BCQEWHWNvbnRhY3RAd29y
# a3BsYWNlY2xvdWRodWIuY29tAhAebu87xzjhs0Q4yPEDH+JoMA0GCWCGSAFlAwQC
# AQUAoIGEMBgGCisGAQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJKoZIhvcNAQkDMQwG
# CisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZI
# hvcNAQkEMSIEIAEGwBx1kbtXalkv7zUwU6H1jQzUX123D3gkbyg35VkVMA0GCSqG
# SIb3DQEBAQUABIIBgCqt/OgX8MTC1OV4EK/jGkOzj4lNPohthRixgN+pYk+r938A
# VkWPNAap4N0A29kd1ujqVYWAGytquYeHjuCK0mAeneEDqwkvyHyeVcw1pvwrzgii
# RRPKqoXX2KyQZ97ADk3Nv1B+9jkZFKjR/8C4b7uVgJzqc+DDvCRczZ0luY3haihA
# YQ0ODJY+XuyY2rX2cifao32bMdofDJE9pWwYOU2sEZRbCrnIsGh4Tl1tZ3cX4Scs
# hRgBGxFLLfA58ehd0Sp/avZexfJps2OEN8CNFNEqR3Sbe9NYkCS6/xwaTjz6CTxe
# +H7HtYPIushYZxjkDjeWMvrc1xbusLFEP/VYO8b7ysowsjuu+47kgGQMBz4D/xg1
# h5iTCHk98pz60ATnWJ2l7ciuqRJv+B3bSSX1mNHQzVp+kAYwjHnXyvqZt5ncnV3J
# DxaikatgyHd/0WVJDaGuu0pUOAvId+05oWX21LuB3TJJp43Hz7R1P21oZT6fR8AM
# ppDV25lkYYivJen8+aGCAyYwggMiBgkqhkiG9w0BCQYxggMTMIIDDwIBATB9MGkx
# CzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjFBMD8GA1UEAxM4
# RGlnaUNlcnQgVHJ1c3RlZCBHNCBUaW1lU3RhbXBpbmcgUlNBNDA5NiBTSEEyNTYg
# MjAyNSBDQTECEAqA7xhLjfEFgtHEdqeVdGgwDQYJYIZIAWUDBAIBBQCgaTAYBgkq
# hkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0yNjA3MTMwODUw
# MTJaMC8GCSqGSIb3DQEJBDEiBCBlpBlTvqMHgd3ZnYpgmvwXyyDgW7fucFp4kI9S
# NIvZQjANBgkqhkiG9w0BAQEFAASCAgC1AukilnWdXSashZYeH8374P2/B0POYel7
# IgUlc4Wi5Yy2Bt9eR40EwDAO8GB6B97Douh46stV5/V4IoCXL2DjVfntME9QIB9i
# s0QRzbc6O4GtCtn31bv3cq8V/eQL/BZGI3zDzUyE7ziJKDw4YSgqO79cJzvDya0E
# XHQDOYLC36L3qYz5bd0r//B7zL0XlWOwn8lQfD8GUoTISUMzi+FfPCZuGEBffU3f
# NXQ8mHiJQByZ1UEHe/lPZTqYMS+cntkpVJfJF5/TrFOZpFM8+japu1ffz2XBJyP1
# 61RUb8FlCGBpafBZwCHBpu/XcfAelu/7VvDWhnDCkHoZvtuzPRkTbnB1pKrfQCQP
# O08zcIYT2cbcdOTjsgn4xLImoF8NsruaM2mtkJIqzV7OJqIQN6jiAyJv2pqvzsTR
# 5u+WItpaZGa1WfO1bHpvJKXT1UmSZpwKJI5scXOw54A/4tzuRbbVUtFD/e3/1bgy
# 8QEb0jLLgJLqxz5EdoWCnwMjuf6bjC3UHK8TV98cV8hWTiwlrI9C5ba8SLRdSIzQ
# aGiw81ZfaZPkEJJdDJ66/9gf3UZq82M9rxBwhtp34GAJRwY1jYauvfOjZRrbTTxH
# NXcvSUVXS6uLkQvT2LMmvlLxWiJ9Zegq3UiNzwuxkiidPKlaJdYhQVtcqMBtmhtF
# MX/DZ3oBxg==
# SIG # End signature block
