<#
.SYNOPSIS
    Compares SharePoint 2019 and SharePoint Online file inventory CSV exports.

.DESCRIPTION
    Compares two CSV files generated by SmartM365-SharePointSource-FileInventory.ps1 and
    SmartM365-SharePointTarget-FileInventory.ps1. The comparison is based on a normalized
    ServerRelativeUrl, with optional path prefixes removed from each side.

    Output files:
    - MissingInTarget.csv: files present in source but missing in target
    - ExtraInTarget.csv: files present in target but missing in source
    - DifferentSize.csv: files present in both but with different SizeBytes
    - Summary.csv: high-level counts

.EXAMPLE
    .\SmartM365-SharePointSourceTarget-FileInventoriesCompare.ps1 `
      -SourceCsv ".\Scans\Source\SP2019-FileInventory-Source-20260529-184257.csv" `
      -TargetCsv ".\Scans\Target\SPO-FileInventory-Target-20260529-194037.csv" `
      -TargetPrefixToRemove "/sites/TargetSite" `
      -ComparisonName "Migration"
.VERSION
    1.0.0
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$SourceCsv,

    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$TargetCsv,

    [string[]]$SourcePrefixToRemove = @(),

    [string[]]$TargetPrefixToRemove = @(),

    [ValidateNotNullOrEmpty()]
    [string]$OutputDirectory,

    [ValidateNotNullOrEmpty()]
    [string]$LogPath,

    [ValidateNotNullOrEmpty()]
    [string]$ComparisonName = 'SharePointInventoryComparison',

    [long]$SizeToleranceBytes = 10240
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
Microsoft.PowerShell.Utility\Write-Host ('{0} Script  : {1} v{2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $MyInvocation.MyCommand.Name, '1.0.0') -ForegroundColor Cyan

function Get-ConsoleTimestamp {
    return (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
}

function Write-Host {
    param(
        [Parameter(Position = 0, ValueFromRemainingArguments = $true)]
        [object[]]$Object,

        [ConsoleColor]$ForegroundColor,

        [switch]$NoNewline
    )

    $message = if ($Object) { ($Object -join ' ') } else { '' }
    $line = if ($message -match '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} ') { $message } else { "{0} {1}" -f (Get-ConsoleTimestamp), $message }
    $parameters = @{ Object = $line }
    if ($PSBoundParameters.ContainsKey('ForegroundColor')) { $parameters.ForegroundColor = $ForegroundColor }
    if ($NoNewline) { $parameters.NoNewline = $true }
    Microsoft.PowerShell.Utility\Write-Host @parameters
}

function Add-TimestampToLogFile {
    param([string]$Path)

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        return
    }

    $timestampPattern = '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} '
    $content = Get-Content -LiteralPath $Path
    $updated = foreach ($line in $content) {
        if ($line -match $timestampPattern -or [string]::IsNullOrWhiteSpace($line)) {
            $line
        }
        else {
            "{0} {1}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $line
        }
    }

    Set-Content -LiteralPath $Path -Value $updated -Encoding UTF8 -WhatIf:$false
}

function Stop-TimestampedTranscript {
    param([string]$Path)

    try {
        Stop-Transcript | Out-Null
    }
    catch {
        return
    }

    Add-TimestampToLogFile -Path $Path
}

function Write-Info {
    param(
        [string]$Message,
        [ConsoleColor]$Color = [ConsoleColor]::Gray
    )

    Write-Host $Message -ForegroundColor $Color
}

function Resolve-InputPath {
    param(
        [string]$Path
    )

    $resolved = Resolve-Path -LiteralPath $Path -ErrorAction Stop
    return $resolved.Path
}

function ConvertTo-NormalizedPath {
    param(
        [string]$Path,
        [string[]]$PrefixesToRemove
    )

    if ([string]::IsNullOrWhiteSpace($Path)) {
        return $null
    }

    $normalized = [System.Uri]::UnescapeDataString($Path.Trim())
    $normalized = $normalized -replace '\\', '/'
    $normalized = $normalized -replace '[?#].*$', ''

    if ($normalized -match '^https?://') {
        try {
            $normalized = ([System.Uri]$normalized).AbsolutePath
        }
        catch {
            return $null
        }
    }

    if (-not $normalized.StartsWith('/')) {
        $normalized = "/$normalized"
    }

    $normalized = $normalized.TrimEnd('/')
    if ([string]::IsNullOrWhiteSpace($normalized)) {
        $normalized = '/'
    }

    foreach ($prefix in $PrefixesToRemove) {
        if ([string]::IsNullOrWhiteSpace($prefix)) {
            continue
        }

        $cleanPrefix = [System.Uri]::UnescapeDataString($prefix.Trim())
        if ($cleanPrefix -match '^https?://') {
            $cleanPrefix = ([System.Uri]$cleanPrefix).AbsolutePath
        }

        if (-not $cleanPrefix.StartsWith('/')) {
            $cleanPrefix = "/$cleanPrefix"
        }

        $cleanPrefix = $cleanPrefix.TrimEnd('/')
        if ([string]::IsNullOrWhiteSpace($cleanPrefix)) {
            continue
        }

        if ($normalized.Equals($cleanPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
            $normalized = '/'
            break
        }

        if ($normalized.StartsWith("$cleanPrefix/", [System.StringComparison]::OrdinalIgnoreCase)) {
            $normalized = $normalized.Substring($cleanPrefix.Length)
            break
        }
    }

    if (-not $normalized.StartsWith('/')) {
        $normalized = "/$normalized"
    }

    $normalized = $normalized -replace '/+', '/'
    return $normalized.ToLowerInvariant()
}

function Get-InventoryKey {
    param(
        $Row,
        [string[]]$PrefixesToRemove
    )

    $path = $Row.ServerRelativeUrl
    if ([string]::IsNullOrWhiteSpace($path)) {
        $path = $Row.FileUrl
    }

    return ConvertTo-NormalizedPath -Path $path -PrefixesToRemove $PrefixesToRemove
}

function ConvertTo-InventoryRecord {
    param(
        $Row,
        [string]$Key
    )

    [pscustomobject]@{
        Key               = $Key
        SiteCollectionUrl = $Row.SiteCollectionUrl
        WebUrl            = $Row.WebUrl
        WebTitle          = $Row.WebTitle
        LibraryTitle      = $Row.LibraryTitle
        FileName          = $Row.FileName
        ServerRelativeUrl = $Row.ServerRelativeUrl
        FileUrl           = $Row.FileUrl
        SizeBytes         = $Row.SizeBytes
        Modified          = $Row.Modified
        ModifiedBy        = $Row.ModifiedBy
    }
}

function Export-Row {
    param(
        [Parameter(Mandatory = $true)]
        $Row,

        [Parameter(Mandatory = $true)]
        [string]$Path,

        [ref]$Created
    )

    if ($Created.Value) {
        $Row | Export-Csv -Delimiter ';' -LiteralPath $Path -NoTypeInformation -Encoding UTF8 -Append
    }
    else {
        $Row | Export-Csv -Delimiter ';' -LiteralPath $Path -NoTypeInformation -Encoding UTF8
        $Created.Value = $true
    }
}

function Get-CsvDelimiter {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    $firstLine = Get-Content -LiteralPath $Path -TotalCount 1
    if (([regex]::Matches($firstLine, ';')).Count -gt ([regex]::Matches($firstLine, ',')).Count) {
        return ';'
    }

    return ','
}

function Import-CsvAutoDelimiter {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    Import-Csv -LiteralPath $Path -Delimiter (Get-CsvDelimiter -Path $Path)
}

function ConvertTo-CsvField {
    param(
        $Value
    )

    if ($null -eq $Value) {
        return '""'
    }

    $text = [string]$Value
    $text = $text.Replace('"', '""')
    return '"' + $text + '"'
}

function Write-CsvRecord {
    param(
        [System.IO.StreamWriter]$Writer,
        [string[]]$Columns,
        $Row
    )

    $values = foreach ($column in $Columns) {
        ConvertTo-CsvField -Value $Row.$column
    }

    $Writer.WriteLine(($values -join ','))
}

function Get-LongValue {
    param(
        $Value
    )

    if ($null -eq $Value -or [string]::IsNullOrWhiteSpace([string]$Value)) {
        return $null
    }

    return [long]$Value
}

$SourceCsv = Resolve-InputPath -Path $SourceCsv
$TargetCsv = Resolve-InputPath -Path $TargetCsv

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $safeName = ($ComparisonName -replace '[\\/:*?"<>|]+', '-').Trim()
    if ([string]::IsNullOrWhiteSpace($safeName)) {
        $safeName = 'SharePointInventoryComparison'
    }

    $scriptDirectory = if ($PSScriptRoot) { $PSScriptRoot } else { (Get-Location).Path }
    $projectDirectory = Split-Path -Path (Split-Path -Path $scriptDirectory -Parent) -Parent
    $OutputDirectory = Join-Path -Path $projectDirectory -ChildPath (Join-Path -Path 'ComparisonResults' -ChildPath ("{0}-{1:yyyyMMdd-HHmmss}" -f $safeName, (Get-Date)))
}

New-Item -Path $OutputDirectory -ItemType Directory -Force | Out-Null

if ([string]::IsNullOrWhiteSpace($LogPath)) {
    $safeLogName = ($ComparisonName -replace '[\\/:*?"<>|]+', '-').Trim()
    if ([string]::IsNullOrWhiteSpace($safeLogName)) {
        $safeLogName = 'SharePointInventoryComparison'
    }
    $LogPath = Join-Path -Path (Join-Path -Path $OutputDirectory -ChildPath 'logs') -ChildPath ("{0}-{1:yyyyMMdd-HHmmss}-Run.log" -f $safeLogName, (Get-Date))
}

$logDirectory = Split-Path -Path $LogPath -Parent
if ($logDirectory -and -not (Test-Path -LiteralPath $logDirectory -PathType Container)) {
    New-Item -ItemType Directory -Path $logDirectory -Force | Out-Null
}

$script:TranscriptStarted = $false
trap {
    if ($script:TranscriptStarted) {
        Stop-TimestampedTranscript -Path $LogPath
    }
    throw $_
}

Start-Transcript -Path $LogPath -Force -WhatIf:$false | Out-Null
$script:TranscriptStarted = $true

$missingPath = Join-Path -Path $OutputDirectory -ChildPath 'MissingInTarget.csv'
$extraPath = Join-Path -Path $OutputDirectory -ChildPath 'ExtraInTarget.csv'
$differentSizePath = Join-Path -Path $OutputDirectory -ChildPath 'DifferentSize.csv'
$summaryPath = Join-Path -Path $OutputDirectory -ChildPath 'Summary.csv'

$inventoryColumns = @(
    'Key',
    'SiteCollectionUrl',
    'WebUrl',
    'WebTitle',
    'LibraryTitle',
    'FileName',
    'ServerRelativeUrl',
    'FileUrl',
    'SizeBytes',
    'Modified',
    'ModifiedBy'
)

$differentSizeColumns = @(
    'Key',
    'SourceSizeBytes',
    'TargetSizeBytes',
    'DeltaBytes',
    'SourceWebUrl',
    'TargetWebUrl',
    'SourceLibraryTitle',
    'TargetLibraryTitle',
    'SourceServerRelativeUrl',
    'TargetServerRelativeUrl',
    'SourceModified',
    'TargetModified'
)

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$missingWriter = New-Object System.IO.StreamWriter($missingPath, $false, $utf8NoBom)
$extraWriter = New-Object System.IO.StreamWriter($extraPath, $false, $utf8NoBom)
$differentSizeWriter = New-Object System.IO.StreamWriter($differentSizePath, $false, $utf8NoBom)

$missingWriter.WriteLine(($inventoryColumns | ForEach-Object { ConvertTo-CsvField -Value $_ }) -join ',')
$extraWriter.WriteLine(($inventoryColumns | ForEach-Object { ConvertTo-CsvField -Value $_ }) -join ',')
$differentSizeWriter.WriteLine(($differentSizeColumns | ForEach-Object { ConvertTo-CsvField -Value $_ }) -join ',')

Write-Info -Color Cyan -Message "Source CSV: $SourceCsv"
Write-Info -Color Cyan -Message "Target CSV: $TargetCsv"
Write-Info -Color Cyan -Message "Output directory: $OutputDirectory"
Write-Info -Color Cyan -Message "Run log: $LogPath"

$sourceIndex = @{}
$sourceTotalRows = 0
$sourceUniqueKeys = 0
$sourceDuplicateKeys = 0

Write-Info -Color Yellow -Message 'Indexing source inventory...'
Import-CsvAutoDelimiter -Path $SourceCsv | ForEach-Object {
    $sourceTotalRows++
    $key = Get-InventoryKey -Row $_ -PrefixesToRemove $SourcePrefixToRemove
    if ([string]::IsNullOrWhiteSpace($key)) {
        return
    }

    if ($sourceIndex.ContainsKey($key)) {
        $sourceDuplicateKeys++
        return
    }

    $sourceIndex[$key] = ConvertTo-InventoryRecord -Row $_ -Key $key
    $sourceUniqueKeys++
}

Write-Info -Color Green -Message ("Source rows: {0}; unique keys: {1}; duplicate keys ignored: {2}" -f $sourceTotalRows, $sourceUniqueKeys, $sourceDuplicateKeys)

$targetSeenKeys = New-Object 'System.Collections.Generic.HashSet[string]' ([System.StringComparer]::OrdinalIgnoreCase)
$targetTotalRows = 0
$targetUniqueKeys = 0
$targetDuplicateKeys = 0
$matched = 0
$extra = 0
$differentSize = 0

Write-Info -Color Yellow -Message 'Comparing target inventory...'
Import-CsvAutoDelimiter -Path $TargetCsv | ForEach-Object {
    $targetTotalRows++
    $key = Get-InventoryKey -Row $_ -PrefixesToRemove $TargetPrefixToRemove
    if ([string]::IsNullOrWhiteSpace($key)) {
        return
    }

    if (-not $targetSeenKeys.Add($key)) {
        $targetDuplicateKeys++
        return
    }

    $targetUniqueKeys++
    $targetRecord = ConvertTo-InventoryRecord -Row $_ -Key $key

    if (-not $sourceIndex.ContainsKey($key)) {
        $extra++
        Write-CsvRecord -Writer $extraWriter -Columns $inventoryColumns -Row $targetRecord
        return
    }

    $matched++
    $sourceRecord = $sourceIndex[$key]
    $sourceSize = Get-LongValue -Value $sourceRecord.SizeBytes
    $targetSize = Get-LongValue -Value $targetRecord.SizeBytes

    if ($null -ne $sourceSize -and $null -ne $targetSize -and [math]::Abs($sourceSize - $targetSize) -gt $SizeToleranceBytes) {
        $differentSize++
        Write-CsvRecord -Writer $differentSizeWriter -Columns $differentSizeColumns -Row ([pscustomobject]@{
            Key                     = $key
            SourceSizeBytes          = $sourceSize
            TargetSizeBytes          = $targetSize
            DeltaBytes               = $targetSize - $sourceSize
            SourceWebUrl             = $sourceRecord.WebUrl
            TargetWebUrl             = $targetRecord.WebUrl
            SourceLibraryTitle       = $sourceRecord.LibraryTitle
            TargetLibraryTitle       = $targetRecord.LibraryTitle
            SourceServerRelativeUrl  = $sourceRecord.ServerRelativeUrl
            TargetServerRelativeUrl  = $targetRecord.ServerRelativeUrl
            SourceModified           = $sourceRecord.Modified
            TargetModified           = $targetRecord.Modified
        })
    }
}

$missing = 0

Write-Info -Color Yellow -Message 'Finding source files missing from target...'
foreach ($entry in $sourceIndex.GetEnumerator()) {
    if (-not $targetSeenKeys.Contains($entry.Key)) {
        $missing++
        Write-CsvRecord -Writer $missingWriter -Columns $inventoryColumns -Row $entry.Value
    }
}

$summary = [pscustomobject]@{
    ComparisonName             = $ComparisonName
    SourceCsv                  = $SourceCsv
    TargetCsv                  = $TargetCsv
    SourceRows                 = $sourceTotalRows
    SourceUniqueKeys           = $sourceUniqueKeys
    SourceDuplicateKeysIgnored = $sourceDuplicateKeys
    TargetRows                 = $targetTotalRows
    TargetUniqueKeys           = $targetUniqueKeys
    TargetDuplicateKeysIgnored = $targetDuplicateKeys
    MatchedKeys                = $matched
    MissingInTarget            = $missing
    ExtraInTarget              = $extra
    DifferentSize              = $differentSize
    SizeToleranceBytes         = $SizeToleranceBytes
    OutputDirectory            = $OutputDirectory
}

$missingWriter.Close()
$extraWriter.Close()
$differentSizeWriter.Close()

$summary | Export-Csv -Delimiter ';' -LiteralPath $summaryPath -NoTypeInformation -Encoding UTF8

Write-Info -Color Green -Message 'Comparison completed.'
Write-Info -Color Green -Message ("Matched: {0}; Missing in target: {1}; Extra in target: {2}; Different size: {3}" -f $matched, $missing, $extra, $differentSize)
Write-Info -Color Cyan -Message "Summary: $summaryPath"

if ($script:TranscriptStarted) {
    Stop-TimestampedTranscript -Path $LogPath
    $script:TranscriptStarted = $false
}

# SIG # Begin signature block
# MIIeYwYJKoZIhvcNAQcCoIIeVDCCHlACAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBLXfHLOER6xBoT
# NvdSSRN0Bo4/m5HbQUqw8gBCyRXsmqCCF/swggS9MIIDJaADAgECAhAebu87xzjh
# s0Q4yPEDH+JoMA0GCSqGSIb3DQEBCwUAME4xHjAcBgNVBAMMFXdvcmtwbGFjZWNs
# b3VkaHViLmNvbTEsMCoGCSqGSIb3DQEJARYdY29udGFjdEB3b3JrcGxhY2VjbG91
# ZGh1Yi5jb20wHhcNMjYwNzEzMDgyMjM1WhcNMjkwNzEzMDgzMjI5WjBOMR4wHAYD
# VQQDDBV3b3JrcGxhY2VjbG91ZGh1Yi5jb20xLDAqBgkqhkiG9w0BCQEWHWNvbnRh
# Y3RAd29ya3BsYWNlY2xvdWRodWIuY29tMIIBojANBgkqhkiG9w0BAQEFAAOCAY8A
# MIIBigKCAYEAse6XztERSyHn9DVqj8Rdv0qjc5owqvgAIGaYxBmfiQuoM48Fo4Xt
# 1ovi9brLUtf55G4XgthNPCoanxfCRRg30IVRxaDfdPXJzYmgsM5tXlsuNU49lE7E
# PJk3+jEOgSCt8NKzmVPKpNRG0NmK0a8wm12cceYZOZlSYE0+ZtT6wy5PQQjMUqIx
# XnGjt4H0nfgZZa7D4FyARKOVg/Xr9sUq5jIn3zszvg4jjeb4b0DKJtfbHukhWc2Y
# oVFgswxVBXCWIaBnfF/cjqMfK/CaToT2trVb4hG4qcQ31s1nR4keoRaOw/vyd6ap
# rEtCsT22N/Jx0dz7fIo1tVyvIaVcHdN9LW3chn0en0OKZ6Ke1OH9wf2prl4KA6Ww
# VzrAZrOlXTAItdK7D9kKO/HeJd4PZvO53oy1LdmMGLSz3OLB9e5q7yo8rfqi5Ka9
# KzM2CrSzz1yphn/H90wz7Q2pm4FIlWdcj86A/0kmhYg+5Wqqbg1drrPXu4nEBwWN
# /dzoGtKZKHTdAgMBAAGjgZYwgZMwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoG
# CCsGAQUFBwMDMD8GA1UdEQQ4MDaBHWNvbnRhY3RAd29ya3BsYWNlY2xvdWRodWIu
# Y29tghV3b3JrcGxhY2VjbG91ZGh1Yi5jb20wDAYDVR0TAQH/BAIwADAdBgNVHQ4E
# FgQUXIOOADQM78XfPAncirgCECedg9gwDQYJKoZIhvcNAQELBQADggGBADhZUB2R
# 5J/Jw030xodhEWeCQ0vnJRaiEsjOxuArQREKH3lCrQ3UsUVl292d6LnQUSTH/jF7
# rovEZ+JN2GQ/LCrXRaCuwCEGZKzlSEbtYWhfwDyj6GpIPq8Y4SeXyjdq4/rrI1bm
# iTK4Sq7EoBlGJuX6l2nfvx1tTioSr11FoDfllJR7EYawRj9hBFJ0gG0b2SuYZMgW
# gaDKefcnJDmOwcRNAZUII0ss8EeyANukWSkNN5ILZ+iKDpQgZxgDLPTiRguCyx45
# PI5wrVTjV/pR7IrtSIfq8UladlrSZJyyDn3NV2ATvIZ6wNxbTmPFcE0uMg/EYzwd
# Tek+CgXL3TxUKeldJM4YDWPimNBRhOPXzBDiOQIj6WNswt/KM1oDLnA00CNtciPN
# dn+dXlneMvTEUah9wyt8o8tkLpoBw+KN+Bq/K0O1qPtS7umi70l45pPiej+mwbwq
# ztcaoVD7a8ggHP1Vdp/rnafM4GtyCAE6b7U9Yzgvp1/a1kh7XffmqVhRRjCCBY0w
# ggR1oAMCAQICEA6bGI750C3n79tQ4ghAGFowDQYJKoZIhvcNAQEMBQAwZTELMAkG
# A1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3LmRp
# Z2ljZXJ0LmNvbTEkMCIGA1UEAxMbRGlnaUNlcnQgQXNzdXJlZCBJRCBSb290IENB
# MB4XDTIyMDgwMTAwMDAwMFoXDTMxMTEwOTIzNTk1OVowYjELMAkGA1UEBhMCVVMx
# FTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNv
# bTEhMB8GA1UEAxMYRGlnaUNlcnQgVHJ1c3RlZCBSb290IEc0MIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAv+aQc2jeu+RdSjwwIjBpM+zCpyUuySE98orY
# WcLhKac9WKt2ms2uexuEDcQwH/MbpDgW61bGl20dq7J58soR0uRf1gU8Ug9SH8ae
# FaV+vp+pVxZZVXKvaJNwwrK6dZlqczKU0RBEEC7fgvMHhOZ0O21x4i0MG+4g1ckg
# HWMpLc7sXk7Ik/ghYZs06wXGXuxbGrzryc/NrDRAX7F6Zu53yEioZldXn1RYjgwr
# t0+nMNlW7sp7XeOtyU9e5TXnMcvak17cjo+A2raRmECQecN4x7axxLVqGDgDEI3Y
# 1DekLgV9iPWCPhCRcKtVgkEy19sEcypukQF8IUzUvK4bA3VdeGbZOjFEmjNAvwjX
# WkmkwuapoGfdpCe8oU85tRFYF/ckXEaPZPfBaYh2mHY9WV1CdoeJl2l6SPDgohIb
# Zpp0yt5LHucOY67m1O+SkjqePdwA5EUlibaaRBkrfsCUtNJhbesz2cXfSwQAzH0c
# lcOP9yGyshG3u3/y1YxwLEFgqrFjGESVGnZifvaAsPvoZKYz0YkH4b235kOkGLim
# dwHhD5QMIR2yVCkliWzlDlJRR3S+Jqy2QXXeeqxfjT/JvNNBERJb5RBQ6zHFynIW
# IgnffEx1P2PsIV/EIFFrb7GrhotPwtZFX50g/KEexcCPorF+CiaZ9eRpL5gdLfXZ
# qbId5RsCAwEAAaOCATowggE2MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFOzX
# 44LScV1kTN8uZz/nupiuHA9PMB8GA1UdIwQYMBaAFEXroq/0ksuCMS1Ri6enIZ3z
# bcgPMA4GA1UdDwEB/wQEAwIBhjB5BggrBgEFBQcBAQRtMGswJAYIKwYBBQUHMAGG
# GGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBDBggrBgEFBQcwAoY3aHR0cDovL2Nh
# Y2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0QXNzdXJlZElEUm9vdENBLmNydDBF
# BgNVHR8EPjA8MDqgOKA2hjRodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNl
# cnRBc3N1cmVkSURSb290Q0EuY3JsMBEGA1UdIAQKMAgwBgYEVR0gADANBgkqhkiG
# 9w0BAQwFAAOCAQEAcKC/Q1xV5zhfoKN0Gz22Ftf3v1cHvZqsoYcs7IVeqRq7IviH
# GmlUIu2kiHdtvRoU9BNKei8ttzjv9P+Aufih9/Jy3iS8UgPITtAq3votVs/59Pes
# MHqai7Je1M/RQ0SbQyHrlnKhSLSZy51PpwYDE3cnRNTnf+hZqPC/Lwum6fI0POz3
# A8eHqNJMQBk1RmppVLC4oVaO7KTVPeix3P0c2PR3WlxUjG/voVA9/HYJaISfb8rb
# II01YBwCA8sgsKxYoA5AY8WYIsGyWfVVa88nq2x2zm8jLfR+cWojayL/ErhULSd+
# 2DrZ8LaHlv1b0VysGMNNn3O3AamfV6peKOK5lDCCBrQwggScoAMCAQICEA3HrFcF
# /yGZLkBDIgw6SYYwDQYJKoZIhvcNAQELBQAwYjELMAkGA1UEBhMCVVMxFTATBgNV
# BAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTEhMB8G
# A1UEAxMYRGlnaUNlcnQgVHJ1c3RlZCBSb290IEc0MB4XDTI1MDUwNzAwMDAwMFoX
# DTM4MDExNDIzNTk1OVowaTELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0
# LCBJbmMuMUEwPwYDVQQDEzhEaWdpQ2VydCBUcnVzdGVkIEc0IFRpbWVTdGFtcGlu
# ZyBSU0E0MDk2IFNIQTI1NiAyMDI1IENBMTCCAiIwDQYJKoZIhvcNAQEBBQADggIP
# ADCCAgoCggIBALR4MdMKmEFyvjxGwBysddujRmh0tFEXnU2tjQ2UtZmWgyxU7UNq
# EY81FzJsQqr5G7A6c+Gh/qm8Xi4aPCOo2N8S9SLrC6Kbltqn7SWCWgzbNfiR+2fk
# HUiljNOqnIVD/gG3SYDEAd4dg2dDGpeZGKe+42DFUF0mR/vtLa4+gKPsYfwEu7EE
# bkC9+0F2w4QJLVSTEG8yAR2CQWIM1iI5PHg62IVwxKSpO0XaF9DPfNBKS7Zazch8
# NF5vp7eaZ2CVNxpqumzTCNSOxm+SAWSuIr21Qomb+zzQWKhxKTVVgtmUPAW35xUU
# FREmDrMxSNlr/NsJyUXzdtFUUt4aS4CEeIY8y9IaaGBpPNXKFifinT7zL2gdFpBP
# 9qh8SdLnEut/GcalNeJQ55IuwnKCgs+nrpuQNfVmUB5KlCX3ZA4x5HHKS+rqBvKW
# xdCyQEEGcbLe1b8Aw4wJkhU1JrPsFfxW1gaou30yZ46t4Y9F20HHfIY4/6vHespY
# MQmUiote8ladjS/nJ0+k6MvqzfpzPDOy5y6gqztiT96Fv/9bH7mQyogxG9QEPHrP
# V6/7umw052AkyiLA6tQbZl1KhBtTasySkuJDpsZGKdlsjg4u70EwgWbVRSX1Wd4+
# zoFpp4Ra+MlKM2baoD6x0VR4RjSpWM8o5a6D8bpfm4CLKczsG7ZrIGNTAgMBAAGj
# ggFdMIIBWTASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBTvb1NK6eQGfHrK
# 4pBW9i/USezLTjAfBgNVHSMEGDAWgBTs1+OC0nFdZEzfLmc/57qYrhwPTzAOBgNV
# HQ8BAf8EBAMCAYYwEwYDVR0lBAwwCgYIKwYBBQUHAwgwdwYIKwYBBQUHAQEEazBp
# MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wQQYIKwYBBQUH
# MAKGNWh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRS
# b290RzQuY3J0MEMGA1UdHwQ8MDowOKA2oDSGMmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0
# LmNvbS9EaWdpQ2VydFRydXN0ZWRSb290RzQuY3JsMCAGA1UdIAQZMBcwCAYGZ4EM
# AQQCMAsGCWCGSAGG/WwHATANBgkqhkiG9w0BAQsFAAOCAgEAF877FoAc/gc9EXZx
# ML2+C8i1NKZ/zdCHxYgaMH9Pw5tcBnPw6O6FTGNpoV2V4wzSUGvI9NAzaoQk97fr
# PBtIj+ZLzdp+yXdhOP4hCFATuNT+ReOPK0mCefSG+tXqGpYZ3essBS3q8nL2UwM+
# NMvEuBd/2vmdYxDCvwzJv2sRUoKEfJ+nN57mQfQXwcAEGCvRR2qKtntujB71WPYA
# gwPyWLKu6RnaID/B0ba2H3LUiwDRAXx1Neq9ydOal95CHfmTnM4I+ZI2rVQfjXQA
# 1WSjjf4J2a7jLzWGNqNX+DF0SQzHU0pTi4dBwp9nEC8EAqoxW6q17r0z0noDjs6+
# BFo+z7bKSBwZXTRNivYuve3L2oiKNqetRHdqfMTCW/NmKLJ9M+MtucVGyOxiDf06
# VXxyKkOirv6o02OoXN4bFzK0vlNMsvhlqgF2puE6FndlENSmE+9JGYxOGLS/D284
# NHNboDGcmWXfwXRy4kbu4QFhOm0xJuF2EZAOk5eCkhSxZON3rGlHqhpB/8MluDez
# ooIs8CVnrpHMiD2wL40mm53+/j7tFaxYKIqL0Q4ssd8xHZnIn/7GELH3IdvG2XlM
# 9q7WP/UwgOkw/HQtyRN62JK4S1C8uw3PdBunvAZapsiI5YKdvlarEvf8EA+8hcpS
# M9LHJmyrxaFtoza2zNaQ9k+5t1wwggbtMIIE1aADAgECAhAIT9wzT35FTtvDD4/5
# khg1MA0GCSqGSIb3DQEBCwUAMGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdp
# Q2VydCwgSW5jLjFBMD8GA1UEAxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBUaW1lU3Rh
# bXBpbmcgUlNBNDA5NiBTSEEyNTYgMjAyNSBDQTEwHhcNMjYwODA1MDAwMDAwWhcN
# MzcxMTA0MjM1OTU5WjBjMQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQs
# IEluYy4xOzA5BgNVBAMTMkRpZ2lDZXJ0IFNIQTI1NiBSU0E0MDk2IFRpbWVzdGFt
# cCBSZXNwb25kZXIgMjAyNiAxMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
# AgEAtnum8sn+zUr41JtMZbP9OMYw+HwJDpG5xkIu/lqcfNYmMX81YmsUiHLbh9yk
# peWBGKTLhYBrAN9Tdg/QEzG32XcObmgIblnr0CoQ3WSAeDZ6nH6X6VkFyYkJw3QB
# JREwvm4UhLzSxmwPA7cFKRTEOMsmEEj6qJk/dqLEAL+oQYuOwE2UuiX1Vnul8YRe
# IyWd4kgLn9gq6LNXM0UplkR6jL/QHxmb6fMoGBJYbnaUI7XD6cKDpekK2SVMld4i
# DbzeHDtOaaxldH5IxuNusQ69nd8/ZXEiB5Hbxj3RlK13cX1W4DlFXKdv/CEhM8Cj
# 1vvlmvhNroyPdRGbbpBlgyf8Wdu5N6ByhFwURn0U6ozlPoxN22v+fviUhP+6DR54
# 7OZnpBMWDfei1f5sVGwiiW/KQTWOK97g+4RJpPzPNV4VYMAwO2jM2Aty2QYPVmOQ
# TJm0msuXnJrSbl2gf9JylpkJlWXqk1Q4LJsxz+TELoQCZIljbgvTJgoPU2R12ydv
# 8i1UqL/adelA0y7U9Pmmtbze9Xx3rtajC5SzQd1jgfwAwsa90v9YcSPdmeoyoBBA
# /27cCL237l5DTYYPDLQ4ON3OLTGWnvRb6jDrf/T75gMRfUzSLCBQfBusm9+mSWRl
# C/Df6S/e9Q8i13CuhzOT2Jx+V/nlbXM4QoBwlUAhelwwJT0CAwEAAaOCAZUwggGR
# MAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFBTJY4owLtRK+26U8+bjQH717M3iMB8G
# A1UdIwQYMBaAFO9vU0rp5AZ8esrikFb2L9RJ7MtOMA4GA1UdDwEB/wQEAwIHgDAW
# BgNVHSUBAf8EDDAKBggrBgEFBQcDCDCBlQYIKwYBBQUHAQEEgYgwgYUwJAYIKwYB
# BQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBdBggrBgEFBQcwAoZRaHR0
# cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZEc0VGltZVN0
# YW1waW5nUlNBNDA5NlNIQTI1NjIwMjVDQTEuY3J0MF8GA1UdHwRYMFYwVKBSoFCG
# Tmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRHNFRpbWVT
# dGFtcGluZ1JTQTQwOTZTSEEyNTYyMDI1Q0ExLmNybDAgBgNVHSAEGTAXMAgGBmeB
# DAEEAjALBglghkgBhv1sBwEwDQYJKoZIhvcNAQELBQADggIBAI3FOmEenVIK35ms
# CYB+fShAsWvSYvLBItoNdAgQ2jIqrGsVsluXMJU/+mRebBc52s6lbKAvOVPXaizm
# KkMLLflEEKDZQx4CkS2t8aHPjkXha3hYZ010htFa3dhNgmalH5vuWvh3tTCf4frT
# S7gPtGc4Z/xaPhQ2AB1mR8eEe/WbH0RWHvVIl6VwQ3+g5FKNfN2N/DWJkf13w2H+
# 2GfqEfbd35Ww8CvoYBjLNIDTadcPWdgsjsiOaK/7EsKJgLjUNIVgvcaFOLLQ/Glr
# A+0ZHJoFUbOr5SJN8zykPspXIXlpDJY/gqFUZRROeab9GVgmhbdOJcD/63RhxPah
# FUGbckRONqMe6DYAv6/mOG0pWd3cPStsdcS7buj5DyniwRY8yooMH6ptx5vpP/pZ
# zBPBeZD2U4IsthyxB5Jaa8qrOkB5z160TXiM5ADMspZ0TfD9MJoq0tFpFPssKRFh
# WeEDYPvcUuN7U7lvcdHl4ezQ3NT/7Ffs1sR1yh/LRbdZ3B3Vc6q2WmD8mDC0p9kz
# l2o73iVtS946IkEj7FkRsZGww1teYxERROC745xrtjvcw9ZyyUjHZWGRIpJeMNsP
# quCDf0fkyHtB+J4AiNZqCQk23rxh+KbpyMTNVKItJ5l92Svl20U9NbqMBOVYl1h5
# 4NEYLJq1/xHWFKPNK903zJZA9P2DMYIFvjCCBboCAQEwYjBOMR4wHAYDVQQDDBV3
# b3JrcGxhY2VjbG91ZGh1Yi5jb20xLDAqBgkqhkiG9w0BCQEWHWNvbnRhY3RAd29y
# a3BsYWNlY2xvdWRodWIuY29tAhAebu87xzjhs0Q4yPEDH+JoMA0GCWCGSAFlAwQC
# AQUAoIGEMBgGCisGAQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJKoZIhvcNAQkDMQwG
# CisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZI
# hvcNAQkEMSIEICkTbtgH4j49CcOGVXswoHZ75x4o6xQUTj6yNPovATNqMA0GCSqG
# SIb3DQEBAQUABIIBgDC7/xjRFJQ0L8Tp9sXLVeCqtndOWpCeMHBrWjX/GhJE7deI
# 0k0W3n5CU3s3lBbleN+/WW0SgCYcb36+Pj1yZE8Rz3V11JWsFbp1ilnT9E5SqO0t
# h05xiunv7LThjgCG47kKZnlh4/mq8QVWpbhyHxS4zCZOYIJSNHunOwkzmqeRtzCz
# WNaxdUpINH/A467GMm7yQwu/kVHERYYrBQtAOEsQlEDTRL88fuy/R6pbNDBUBGHr
# uKZ+avBYVdunX2HG47j4AsnSTCCLF3bA79LijakQMWMY/miR9vrWIv1fcE4tXlzf
# gc3qdec1o/rAiglNFUYLBqXBzUu/jWd+C3X29RtGE/6efwOIdQFZpFfpprSLiBQx
# KshypxU1ROUL6kclFqrLGxt68Nxyp14Dp0DQhn/uGjH5H5nyYh0a7cUcyVDsCfz7
# 1r5qzqukXk9DPJ2oQJLINec3q03cWu9NeAS4ujCArYzkaaH4qeS3XjFXl4NVyGAa
# HoZLMKVEzsUq4M+IrKGCAyYwggMiBgkqhkiG9w0BCQYxggMTMIIDDwIBATB9MGkx
# CzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjFBMD8GA1UEAxM4
# RGlnaUNlcnQgVHJ1c3RlZCBHNCBUaW1lU3RhbXBpbmcgUlNBNDA5NiBTSEEyNTYg
# MjAyNSBDQTECEAhP3DNPfkVO28MPj/mSGDUwDQYJYIZIAWUDBAIBBQCgaTAYBgkq
# hkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0yNjEwMDMwMDE5
# MDRaMC8GCSqGSIb3DQEJBDEiBCAJoskVGJ8uqTjt6XjbWB82HbtVUJA8/VEXU2ME
# N2loETANBgkqhkiG9w0BAQEFAASCAgCJrjjw8qE5AUc30RtxKTXsdoQKU2KI/QwZ
# bsSPsQCl63660HK1+AKG9ywWDRFaPYnzmLPjJR2bKaP5qKiOWq4UHqVwc+DMgr+k
# VsmL1ECKNFbBW07duMs1nHBwqkr9URY0wH4wXsAsMhC7AaanBrW5LpxiKFaTC7x9
# mskgcUYKQ4OZaBkkiONxKDhPjnyBem1xcG82szuJSd4231GnsGpLiofHaw4BoWwb
# n2GIUs8z5+8l1XYk7Dt/AQTIjrTvEaqVc9MmtiSl7I6yTeV1O4+8aRXwOLWcPGlE
# h/+ZHBpFwyN9oc/b0aoVCpfzsIHTUmC0cycLvdffuDISnl7wfP7+DVFzP7JyNYdR
# WLF9MYpGZ8rzRXAE0F3lz3dZMETDcvoTkAmMDMDek6RprXvJJ5NNXH0AHclIqw6F
# xFVu2xC2LXs3N/r4I/5hXk8lV5CbuKDIzULIUCQrNH0TXWIpU3BI/vBbCAu9UzfY
# CrCgvv5k8r3iNQNtnyLEOd6fZO5BOlbH3QGPiELQRzLbO6si+HqQFyfiiVKJaoUk
# UU4zdAR3yQ5w8YqM8LSDoyx8HDt3/jmjGve5ybOtzdpBdIAmEk5s4squ/1MDPuBz
# hzE1B9vQP9Yl9M7WRrN3hHWQH+GrZzhKxf7E6eOSFQFH0IVdgVdGROX7zxyZKg8N
# Bv4wGbkaAA==
# SIG # End signature block
