<#
.SYNOPSIS
    Compares SharePoint 2019 and SharePoint Online file inventory CSV exports.

.DESCRIPTION
    Compares two CSV files generated by SmartM365-SharePointSource-FileInventory.ps1 and
    SmartM365-SharePointTarget-FileInventory.ps1. The comparison is based on a normalized
    ServerRelativeUrl, with optional path prefixes removed from each side.

    Output files:
    - MissingInTarget.csv: files present in source but missing in target
    - ExtraInTarget.csv: files present in target but missing in source
    - DifferentSize.csv: files present in both but with different SizeBytes
    - Summary.csv: high-level counts

.EXAMPLE
    .\SmartM365-SharePointSourceTarget-FileInventoriesCompare.ps1 `
      -SourceCsv ".\Scans\Source\SP2019-FileInventory-Source-20260529-184257.csv" `
      -TargetCsv ".\Scans\Target\SPO-FileInventory-Target-20260529-194037.csv" `
      -TargetPrefixToRemove "/sites/TargetSite" `
      -ComparisonName "Migration"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$SourceCsv,

    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$TargetCsv,

    [string[]]$SourcePrefixToRemove = @(),

    [string[]]$TargetPrefixToRemove = @(),

    [ValidateNotNullOrEmpty()]
    [string]$OutputDirectory,

    [ValidateNotNullOrEmpty()]
    [string]$LogPath,

    [ValidateNotNullOrEmpty()]
    [string]$ComparisonName = 'SharePointInventoryComparison',

    [long]$SizeToleranceBytes = 10240
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

function Get-ConsoleTimestamp {
    return (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
}

function Write-Host {
    param(
        [Parameter(Position = 0, ValueFromRemainingArguments = $true)]
        [object[]]$Object,

        [ConsoleColor]$ForegroundColor,

        [switch]$NoNewline
    )

    $message = if ($Object) { ($Object -join ' ') } else { '' }
    $line = if ($message -match '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} ') { $message } else { "{0} {1}" -f (Get-ConsoleTimestamp), $message }
    $parameters = @{ Object = $line }
    if ($PSBoundParameters.ContainsKey('ForegroundColor')) { $parameters.ForegroundColor = $ForegroundColor }
    if ($NoNewline) { $parameters.NoNewline = $true }
    Microsoft.PowerShell.Utility\Write-Host @parameters
}

function Add-TimestampToLogFile {
    param([string]$Path)

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        return
    }

    $timestampPattern = '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} '
    $content = Get-Content -LiteralPath $Path
    $updated = foreach ($line in $content) {
        if ($line -match $timestampPattern -or [string]::IsNullOrWhiteSpace($line)) {
            $line
        }
        else {
            "{0} {1}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $line
        }
    }

    Set-Content -LiteralPath $Path -Value $updated -Encoding UTF8 -WhatIf:$false
}

function Stop-TimestampedTranscript {
    param([string]$Path)

    try {
        Stop-Transcript | Out-Null
    }
    catch {
        return
    }

    Add-TimestampToLogFile -Path $Path
}

function Write-Info {
    param(
        [string]$Message,
        [ConsoleColor]$Color = [ConsoleColor]::Gray
    )

    Write-Host $Message -ForegroundColor $Color
}

function Resolve-InputPath {
    param(
        [string]$Path
    )

    $resolved = Resolve-Path -LiteralPath $Path -ErrorAction Stop
    return $resolved.Path
}

function ConvertTo-NormalizedPath {
    param(
        [string]$Path,
        [string[]]$PrefixesToRemove
    )

    if ([string]::IsNullOrWhiteSpace($Path)) {
        return $null
    }

    $normalized = [System.Uri]::UnescapeDataString($Path.Trim())
    $normalized = $normalized -replace '\\', '/'
    $normalized = $normalized -replace '[?#].*$', ''

    if ($normalized -match '^https?://') {
        try {
            $normalized = ([System.Uri]$normalized).AbsolutePath
        }
        catch {
            return $null
        }
    }

    if (-not $normalized.StartsWith('/')) {
        $normalized = "/$normalized"
    }

    $normalized = $normalized.TrimEnd('/')
    if ([string]::IsNullOrWhiteSpace($normalized)) {
        $normalized = '/'
    }

    foreach ($prefix in $PrefixesToRemove) {
        if ([string]::IsNullOrWhiteSpace($prefix)) {
            continue
        }

        $cleanPrefix = [System.Uri]::UnescapeDataString($prefix.Trim())
        if ($cleanPrefix -match '^https?://') {
            $cleanPrefix = ([System.Uri]$cleanPrefix).AbsolutePath
        }

        if (-not $cleanPrefix.StartsWith('/')) {
            $cleanPrefix = "/$cleanPrefix"
        }

        $cleanPrefix = $cleanPrefix.TrimEnd('/')
        if ([string]::IsNullOrWhiteSpace($cleanPrefix)) {
            continue
        }

        if ($normalized.Equals($cleanPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
            $normalized = '/'
            break
        }

        if ($normalized.StartsWith("$cleanPrefix/", [System.StringComparison]::OrdinalIgnoreCase)) {
            $normalized = $normalized.Substring($cleanPrefix.Length)
            break
        }
    }

    if (-not $normalized.StartsWith('/')) {
        $normalized = "/$normalized"
    }

    $normalized = $normalized -replace '/+', '/'
    return $normalized.ToLowerInvariant()
}

function Get-InventoryKey {
    param(
        $Row,
        [string[]]$PrefixesToRemove
    )

    $path = $Row.ServerRelativeUrl
    if ([string]::IsNullOrWhiteSpace($path)) {
        $path = $Row.FileUrl
    }

    return ConvertTo-NormalizedPath -Path $path -PrefixesToRemove $PrefixesToRemove
}

function ConvertTo-InventoryRecord {
    param(
        $Row,
        [string]$Key
    )

    [pscustomobject]@{
        Key               = $Key
        SiteCollectionUrl = $Row.SiteCollectionUrl
        WebUrl            = $Row.WebUrl
        WebTitle          = $Row.WebTitle
        LibraryTitle      = $Row.LibraryTitle
        FileName          = $Row.FileName
        ServerRelativeUrl = $Row.ServerRelativeUrl
        FileUrl           = $Row.FileUrl
        SizeBytes         = $Row.SizeBytes
        Modified          = $Row.Modified
        ModifiedBy        = $Row.ModifiedBy
    }
}

function Export-Row {
    param(
        [Parameter(Mandatory = $true)]
        $Row,

        [Parameter(Mandatory = $true)]
        [string]$Path,

        [ref]$Created
    )

    if ($Created.Value) {
        $Row | Export-Csv -Delimiter ';' -LiteralPath $Path -NoTypeInformation -Encoding UTF8 -Append
    }
    else {
        $Row | Export-Csv -Delimiter ';' -LiteralPath $Path -NoTypeInformation -Encoding UTF8
        $Created.Value = $true
    }
}

function Get-CsvDelimiter {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    $firstLine = Get-Content -LiteralPath $Path -TotalCount 1
    if (([regex]::Matches($firstLine, ';')).Count -gt ([regex]::Matches($firstLine, ',')).Count) {
        return ';'
    }

    return ','
}

function Import-CsvAutoDelimiter {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    Import-Csv -LiteralPath $Path -Delimiter (Get-CsvDelimiter -Path $Path)
}

function ConvertTo-CsvField {
    param(
        $Value
    )

    if ($null -eq $Value) {
        return '""'
    }

    $text = [string]$Value
    $text = $text.Replace('"', '""')
    return '"' + $text + '"'
}

function Write-CsvRecord {
    param(
        [System.IO.StreamWriter]$Writer,
        [string[]]$Columns,
        $Row
    )

    $values = foreach ($column in $Columns) {
        ConvertTo-CsvField -Value $Row.$column
    }

    $Writer.WriteLine(($values -join ','))
}

function Get-LongValue {
    param(
        $Value
    )

    if ($null -eq $Value -or [string]::IsNullOrWhiteSpace([string]$Value)) {
        return $null
    }

    return [long]$Value
}

$SourceCsv = Resolve-InputPath -Path $SourceCsv
$TargetCsv = Resolve-InputPath -Path $TargetCsv

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $safeName = ($ComparisonName -replace '[\\/:*?"<>|]+', '-').Trim()
    if ([string]::IsNullOrWhiteSpace($safeName)) {
        $safeName = 'SharePointInventoryComparison'
    }

    $scriptDirectory = if ($PSScriptRoot) { $PSScriptRoot } else { (Get-Location).Path }
    $projectDirectory = Split-Path -Path (Split-Path -Path $scriptDirectory -Parent) -Parent
    $OutputDirectory = Join-Path -Path $projectDirectory -ChildPath (Join-Path -Path 'ComparisonResults' -ChildPath ("{0}-{1:yyyyMMdd-HHmmss}" -f $safeName, (Get-Date)))
}

New-Item -Path $OutputDirectory -ItemType Directory -Force | Out-Null

if ([string]::IsNullOrWhiteSpace($LogPath)) {
    $safeLogName = ($ComparisonName -replace '[\\/:*?"<>|]+', '-').Trim()
    if ([string]::IsNullOrWhiteSpace($safeLogName)) {
        $safeLogName = 'SharePointInventoryComparison'
    }
    $LogPath = Join-Path -Path (Join-Path -Path $OutputDirectory -ChildPath 'logs') -ChildPath ("{0}-{1:yyyyMMdd-HHmmss}-Run.log" -f $safeLogName, (Get-Date))
}

$logDirectory = Split-Path -Path $LogPath -Parent
if ($logDirectory -and -not (Test-Path -LiteralPath $logDirectory -PathType Container)) {
    New-Item -ItemType Directory -Path $logDirectory -Force | Out-Null
}

$script:TranscriptStarted = $false
trap {
    if ($script:TranscriptStarted) {
        Stop-TimestampedTranscript -Path $LogPath
    }
    throw $_
}

Start-Transcript -Path $LogPath -Force -WhatIf:$false | Out-Null
$script:TranscriptStarted = $true

$missingPath = Join-Path -Path $OutputDirectory -ChildPath 'MissingInTarget.csv'
$extraPath = Join-Path -Path $OutputDirectory -ChildPath 'ExtraInTarget.csv'
$differentSizePath = Join-Path -Path $OutputDirectory -ChildPath 'DifferentSize.csv'
$summaryPath = Join-Path -Path $OutputDirectory -ChildPath 'Summary.csv'

$inventoryColumns = @(
    'Key',
    'SiteCollectionUrl',
    'WebUrl',
    'WebTitle',
    'LibraryTitle',
    'FileName',
    'ServerRelativeUrl',
    'FileUrl',
    'SizeBytes',
    'Modified',
    'ModifiedBy'
)

$differentSizeColumns = @(
    'Key',
    'SourceSizeBytes',
    'TargetSizeBytes',
    'DeltaBytes',
    'SourceWebUrl',
    'TargetWebUrl',
    'SourceLibraryTitle',
    'TargetLibraryTitle',
    'SourceServerRelativeUrl',
    'TargetServerRelativeUrl',
    'SourceModified',
    'TargetModified'
)

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$missingWriter = New-Object System.IO.StreamWriter($missingPath, $false, $utf8NoBom)
$extraWriter = New-Object System.IO.StreamWriter($extraPath, $false, $utf8NoBom)
$differentSizeWriter = New-Object System.IO.StreamWriter($differentSizePath, $false, $utf8NoBom)

$missingWriter.WriteLine(($inventoryColumns | ForEach-Object { ConvertTo-CsvField -Value $_ }) -join ',')
$extraWriter.WriteLine(($inventoryColumns | ForEach-Object { ConvertTo-CsvField -Value $_ }) -join ',')
$differentSizeWriter.WriteLine(($differentSizeColumns | ForEach-Object { ConvertTo-CsvField -Value $_ }) -join ',')

Write-Info -Color Cyan -Message "Source CSV: $SourceCsv"
Write-Info -Color Cyan -Message "Target CSV: $TargetCsv"
Write-Info -Color Cyan -Message "Output directory: $OutputDirectory"
Write-Info -Color Cyan -Message "Run log: $LogPath"

$sourceIndex = @{}
$sourceTotalRows = 0
$sourceUniqueKeys = 0
$sourceDuplicateKeys = 0

Write-Info -Color Yellow -Message 'Indexing source inventory...'
Import-CsvAutoDelimiter -Path $SourceCsv | ForEach-Object {
    $sourceTotalRows++
    $key = Get-InventoryKey -Row $_ -PrefixesToRemove $SourcePrefixToRemove
    if ([string]::IsNullOrWhiteSpace($key)) {
        return
    }

    if ($sourceIndex.ContainsKey($key)) {
        $sourceDuplicateKeys++
        return
    }

    $sourceIndex[$key] = ConvertTo-InventoryRecord -Row $_ -Key $key
    $sourceUniqueKeys++
}

Write-Info -Color Green -Message ("Source rows: {0}; unique keys: {1}; duplicate keys ignored: {2}" -f $sourceTotalRows, $sourceUniqueKeys, $sourceDuplicateKeys)

$targetSeenKeys = New-Object 'System.Collections.Generic.HashSet[string]' ([System.StringComparer]::OrdinalIgnoreCase)
$targetTotalRows = 0
$targetUniqueKeys = 0
$targetDuplicateKeys = 0
$matched = 0
$extra = 0
$differentSize = 0

Write-Info -Color Yellow -Message 'Comparing target inventory...'
Import-CsvAutoDelimiter -Path $TargetCsv | ForEach-Object {
    $targetTotalRows++
    $key = Get-InventoryKey -Row $_ -PrefixesToRemove $TargetPrefixToRemove
    if ([string]::IsNullOrWhiteSpace($key)) {
        return
    }

    if (-not $targetSeenKeys.Add($key)) {
        $targetDuplicateKeys++
        return
    }

    $targetUniqueKeys++
    $targetRecord = ConvertTo-InventoryRecord -Row $_ -Key $key

    if (-not $sourceIndex.ContainsKey($key)) {
        $extra++
        Write-CsvRecord -Writer $extraWriter -Columns $inventoryColumns -Row $targetRecord
        return
    }

    $matched++
    $sourceRecord = $sourceIndex[$key]
    $sourceSize = Get-LongValue -Value $sourceRecord.SizeBytes
    $targetSize = Get-LongValue -Value $targetRecord.SizeBytes

    if ($null -ne $sourceSize -and $null -ne $targetSize -and [math]::Abs($sourceSize - $targetSize) -gt $SizeToleranceBytes) {
        $differentSize++
        Write-CsvRecord -Writer $differentSizeWriter -Columns $differentSizeColumns -Row ([pscustomobject]@{
            Key                     = $key
            SourceSizeBytes          = $sourceSize
            TargetSizeBytes          = $targetSize
            DeltaBytes               = $targetSize - $sourceSize
            SourceWebUrl             = $sourceRecord.WebUrl
            TargetWebUrl             = $targetRecord.WebUrl
            SourceLibraryTitle       = $sourceRecord.LibraryTitle
            TargetLibraryTitle       = $targetRecord.LibraryTitle
            SourceServerRelativeUrl  = $sourceRecord.ServerRelativeUrl
            TargetServerRelativeUrl  = $targetRecord.ServerRelativeUrl
            SourceModified           = $sourceRecord.Modified
            TargetModified           = $targetRecord.Modified
        })
    }
}

$missing = 0

Write-Info -Color Yellow -Message 'Finding source files missing from target...'
foreach ($entry in $sourceIndex.GetEnumerator()) {
    if (-not $targetSeenKeys.Contains($entry.Key)) {
        $missing++
        Write-CsvRecord -Writer $missingWriter -Columns $inventoryColumns -Row $entry.Value
    }
}

$summary = [pscustomobject]@{
    ComparisonName             = $ComparisonName
    SourceCsv                  = $SourceCsv
    TargetCsv                  = $TargetCsv
    SourceRows                 = $sourceTotalRows
    SourceUniqueKeys           = $sourceUniqueKeys
    SourceDuplicateKeysIgnored = $sourceDuplicateKeys
    TargetRows                 = $targetTotalRows
    TargetUniqueKeys           = $targetUniqueKeys
    TargetDuplicateKeysIgnored = $targetDuplicateKeys
    MatchedKeys                = $matched
    MissingInTarget            = $missing
    ExtraInTarget              = $extra
    DifferentSize              = $differentSize
    SizeToleranceBytes         = $SizeToleranceBytes
    OutputDirectory            = $OutputDirectory
}

$missingWriter.Close()
$extraWriter.Close()
$differentSizeWriter.Close()

$summary | Export-Csv -Delimiter ';' -LiteralPath $summaryPath -NoTypeInformation -Encoding UTF8

Write-Info -Color Green -Message 'Comparison completed.'
Write-Info -Color Green -Message ("Matched: {0}; Missing in target: {1}; Extra in target: {2}; Different size: {3}" -f $matched, $missing, $extra, $differentSize)
Write-Info -Color Cyan -Message "Summary: $summaryPath"

if ($script:TranscriptStarted) {
    Stop-TimestampedTranscript -Path $LogPath
    $script:TranscriptStarted = $false
}

# SIG # Begin signature block
# MIIHcgYJKoZIhvcNAQcCoIIHYzCCB18CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCC3X4o+RK4g7KPu
# uR/vqYj7ankQUYED9wLv8dx0oGABfqCCBEgwggREMIICrKADAgECAhBxu0EivlCF
# tUbJPfe/Va5qMA0GCSqGSIb3DQEBCwUAMDoxODA2BgNVBAMML1NtYXJ0TTM2NSBP
# cmNoZXN0cmF0b3IgQ29kZSBTaWduaW5nIFNlbGYtU2lnbmVkMB4XDTI2MDcxMTIz
# MTc1MloXDTI5MDcxMTIzMjc1MVowOjE4MDYGA1UEAwwvU21hcnRNMzY1IE9yY2hl
# c3RyYXRvciBDb2RlIFNpZ25pbmcgU2VsZi1TaWduZWQwggGiMA0GCSqGSIb3DQEB
# AQUAA4IBjwAwggGKAoIBgQC4A+QoBzUXkXXMoVrptgMss1BNRwJhNcYop9CKHvJY
# QnBLkhSI10Z7EBCZsDSAfICechL0e7Lrwaz8/sTRQeITCKMRzxFe9Oq1CxZfRUh0
# U1T/m8+9q/OR0C6hCSZ9LvpiZExBSmQsQlXyl8smfFK2+gecLOQUPFD7gcpM03gv
# 6OkX/bLpBQZs52K3RnH+YKje0L6W985qxn1M5nDmC4rc2U90k4evzMMPOjTX7jZA
# PHOT3g6ByPWI2SNowO1ptXheS4KGjbx3IH+4+r4UwIPc32hauiAfjXr63inQdkII
# 7tYVI5GBiJB20Gzujm5KuHU9qVXMvAAk7WR9DBGdH4Pq5Or3WD58KV2Mazx0SWhV
# A4ikEEENTbaWIaFEYgWR2PAtPv7rt/p5ZK05fP7Nt/TfSHzBFQsKS4wFchiWQTVj
# kdAPuzsipnwiJyOSmQ7FppnuuhUxEq9ZkOigDLett9ZoY5oNcASOnpCWnxnWx/aq
# xDuJOnKBOGRly1KFUQ+OABUCAwEAAaNGMEQwDgYDVR0PAQH/BAQDAgeAMBMGA1Ud
# JQQMMAoGCCsGAQUFBwMDMB0GA1UdDgQWBBQkjQccxcT1k6xhYBW0XHlelX6nFjAN
# BgkqhkiG9w0BAQsFAAOCAYEAk3bN0vTJBIFnyLm4zxarRLfr6uEl9Y2Xk4P16AxG
# DDLN+Zd7T+oblgAIz4/0EHPJ3DsonLsjOnZBOp5iJr1nSxBy9Cs6K1T6k2mtSr93
# mOT2MSNDlLOFhk37U46yFDJHfX4rQLTmltOoUpeU7V7Cr5EnWJ4xbdmexZUx5vz+
# qeqqe86VxT00Npb5OXINvs8+gH85J+x4HWmrTDzruME1JLkX388g3AQvVd5Xf0YY
# 2InRPQ7Y0jrzccH6OSz14DHSnzN5pKzVzvv9aFDuZ+gCkbC8ZIr890I8WXxbYskX
# 8bTTP0Sa8Jhw22OCOwzDhFxxqivhbqHRybgQ6KdSoDxS51WHp3saGlWfwmFyWkIe
# L5eEpdz8r2vpTbaJVZnVT/SxpYobgZIn3zbss0JFiltcgguIoc+fNbMEUoqnEARQ
# dD4+fIPF32CUclDI6JpugYJLSuvJt6gy4k78A1jQaYTbdZ6Twt+Pup+3ocnWmeyV
# umYxx47CZmI93XUw5yflFPRUMYICgDCCAnwCAQEwTjA6MTgwNgYDVQQDDC9TbWFy
# dE0zNjUgT3JjaGVzdHJhdG9yIENvZGUgU2lnbmluZyBTZWxmLVNpZ25lZAIQcbtB
# Ir5QhbVGyT33v1WuajANBglghkgBZQMEAgEFAKCBhDAYBgorBgEEAYI3AgEMMQow
# CKACgAChAoAAMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisGAQQBgjcC
# AQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3DQEJBDEiBCC5LgXUTE/rVu1d/mds
# FPQUmVq4QE+Vlzv4gZCeoQA2ZDANBgkqhkiG9w0BAQEFAASCAYBiW1HyjCvl7SJ6
# 6P+pI3r6LLysHctDgvQj5b6SxWmo+L18TEFV/4DkFupsiX3I0Nogg66tsF0xy7+z
# SBuOQ/dGGHNzyzYnsfaw1LnY5yx2dwGTvClvK2PYXNGDLnLXNNxxCmgtH/3O2xQ3
# LYqAcktftXnLXDMaQUI1AE954CeJAqRyJFSkTyleFQNNBEc+HgzAV0GWSlTu6h/z
# r1Wu1RDM3WhWdsKChnBue6yCJJZloOszaXPZQbDmMHGg/eKOmgaPmtvzMCweQCY4
# CBkRrMwmzdXfnD0XK1SB6I7CTKxcyaimfxe2ipVZfOxBxwdNDLOCiapBR4vsZHdo
# 8kMpL2LUVvvESy6Op8bkDxnmcGA635bat1OFI+AsqfjNb5QV6sHAZGX4JNQD5Qx+
# wxh5l6+nR7lAfb8l3Zp2GVj3xf2knIXc8gS4EWOKPRRIWJ5wB/1HP71//pmUTIUj
# CIduah9x5SxA/MTgvZ7KDalcsSsDqGFn3j16ZhBZwywbCF3UsDM=
# SIG # End signature block
