@echo off
setlocal EnableExtensions EnableDelayedExpansion
rem Generated by Orchestrator\New-SmartM365-OrchestratorJobLaunchers.ps1. Do not edit.
rem Usage: Request-SmartM365-OrchestratorJob.cmd JobName[,JobName...] [-IncludeDependencies] [-NoWait]
rem Requests the named jobs through the resident orchestrators and waits for their result.

if "%~1"=="" (
    echo Usage: %~nx0 JobName[,JobName...] [-IncludeDependencies] [-NoWait]
    exit /b 1
)
set "SCRIPT_DIR=%~dp0..\Orchestrator\"
set "PWSH="
set "PWSH_X64=%ProgramFiles%\PowerShell\7\pwsh.exe"
set "PWSH_X86="
if not "%ProgramFiles(x86)%"=="" set "PWSH_X86=%ProgramFiles(x86)%\PowerShell\7\pwsh.exe"
if exist "%PWSH_X64%" set "PWSH=%PWSH_X64%"
if not defined PWSH if defined PWSH_X86 if exist "%PWSH_X86%" set "PWSH=%PWSH_X86%"
if not defined PWSH for /f "delims=" %%I in ('where pwsh.exe 2^>nul') do if not defined PWSH set "PWSH=%%I"
if not defined PWSH (
    echo PowerShell 7 ^(pwsh.exe^) was not found.
    echo Install PowerShell 7 or add pwsh.exe to PATH.
    pause
    exit /b 1
)

"%PWSH%" -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT_DIR%SmartM365-Inventory-Pipeline.ps1" -Tenant prod -Collect -Job %*
set "EXIT_CODE=%ERRORLEVEL%"
exit /b %EXIT_CODE%
