@{
    RootModule = "SmartM365-WindowsPowerShell5.psm1"
    ModuleVersion = "1.0.46"
    GUID = "dde15961-7933-412f-8d09-e1dd8a889b65"
    Author = "Internal automation team"
    CompanyName = "Internal"
    Copyright = "(c) 2025 Internal automation team. All rights reserved."
    Description = "Windows PowerShell 5.1 compatibility module for SmartM365 initialization, logging, cleanup, and cloud session helpers."
    PowerShellVersion = "5.1"
    FunctionsToExport = @(
        "InitializeScriptEnvironment",
        "RemoveOldFiles",
        "Remove-SmartM365TimestampedFilesOlderThan",
        "Remove-SmartM365TimestampedDirectoriesOlderThan",
        "Remove-OldFiles",
        "EnsureExchangePSSnapinLoaded",
        "Format-SmartM365LogLine",
        "Update-SmartM365TimestampedTranscript",
        "Get-SmartM365ModuleDiagnosticText",
        "Write-SmartM365LoadedModuleVersions",
        "Complete-SmartM365ExecutionContext",
        "Write-SmartM365CompletionBanner",
        "WriteLog",
        "Set-SmartM365CoreContext",
        "Get-SmartM365MaxItemsValue",
        "Test-SmartM365MaxItemsMode",
        "Get-SmartM365MaxItemsSuffix",
        "Set-SmartM365MaxItemsMode",
        "Add-SmartM365MaxItemsSuffixToCsvPath",
        "Add-SmartM365MaxItemsSuffixToBaseName",
        "Add-SmartM365MaxItemsMailBanner",
        "Add-SmartM365MaxItemsSubjectPrefix",
        "Get-SmartM365MailTenantName",
        "Format-SmartM365MailSubject",
        "Get-SmartM365MailScriptContext",
        "Add-SmartM365MailExecutionFooter",
        "Limit-SmartM365RowsForMaxItems",
        "Get-SmartM365CsvValidationBaseName",
        "Get-SmartM365CsvValidationRule",
        "Assert-SmartM365CsvDataCompleteness",
        "Add-SmartM365CsvValidationRule",
        "Initialize-SmartM365DefaultCsvValidationRules",
        "Add-SmartM365TenantKey",
        "Repair-SmartM365CsvTenantKeySchema",
        "Write-SmartM365CsvAtomically",
        "Add-SmartM365CsvRowsAtomically",
        "Copy-SmartM365FileAtomically",
        "Write-SmartM365TextAtomically",
        "Publish-SmartM365Csv",
        "Export-SmartM365Csv",
        "Invoke-SmartM365Preflight",
        "Save-SmartM365WeeklyInventoryHistory",
        "Add-SmartM365WeeklyHistory",
        "Send-SmartM365TeamsNotification",
        "SendFileListEmailReport",
        "NewTableFilesEmailBody",
        "ConvertTo-SmartM365EmailHtmlText",
        "ConvertTo-SmartM365ConfigBoolean",
        "Get-SmartM365MailBrandingConfig",
        "ConvertTo-SmartM365MailLogoDataUri",
        "Add-SmartM365MailBranding",
        "New-SmartM365EmailBody",
        "ConvertTo-SmartM365EmailBody",
        "ExportAndCopyCsv",
        "ExportAndCopyCsvFromConvert",
        "ConvertTo-SmartM365SharePointDataRootPath",
        "Get-SmartM365SharePointRelativeFilePath",
        "Invoke-SmartM365SharePointCsvUpload",
        "Remove-SmartM365SharePointFile",
        "Remove-SmartM365SharePointTimestampedCsvOlderThan",
        "NewRemoteScheduledTaskAndWait",
        "SendEmailHtmlReport",
        "NewSimpleEmailBody",
        "NewTableEmailBody",
        "GetFileList",
        "Connect-SmartM365CloudSession",
        "Disconnect-SmartM365CloudSession"
    )
    VariablesToExport = @()
    AliasesToExport = @()
}
