# Name: SmartM365-Recovery-Check-Detection.ps1
# Version: 1.0
$taskPath = "\Microsoft\Windows\Workplace Join"
$taskName = "Recovery-Check"

try {
    $task = Get-ScheduledTask -TaskPath $taskPath -TaskName $taskName -ErrorAction Stop

    # Vérifie si la tâche est activée
    if ($task.State -ne "Disabled") {
        # Tâche présente et activée → conforme
        exit 0
    }
    else {
        # Tâche présente mais désactivée → non conforme
        exit 1
    }
}
catch {
    # Tâche absente → non conforme
    exit 1
}

# SIG # Begin signature block
# MIIHJAYJKoZIhvcNAQcCoIIHFTCCBxECAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCD8kq0WaxJ2+5Rl
# HRFgUU4046bFwZzSNLWCxvynw75B86CCBBQwggQQMIICeKADAgECAhBwIfLVIgJW
# v0GFVsTsys9PMA0GCSqGSIb3DQEBCwUAMCAxHjAcBgNVBAMMFXdvcmtwbGFjZWNs
# b3VkaHViLmNvbTAeFw0yNjA3MTIwNjM5MTZaFw0yOTA3MTIwNjQ5MTZaMCAxHjAc
# BgNVBAMMFXdvcmtwbGFjZWNsb3VkaHViLmNvbTCCAaIwDQYJKoZIhvcNAQEBBQAD
# ggGPADCCAYoCggGBAMJqEmY4V9VM4HhTovXPXHSWb44jVYMj05xJIZf2f/NxQLR/
# vfka/0JbdTSRJ03Yy3OIulBP5DqbnfAyzv+9eulPVX/BUFM6b2lENxZpVrvj55TZ
# levsXyzHuK0xs7/FFpbLQ2Ts3LGPJTLlneOfuEWKRT6xTotD1RnElDCumiOnQHOD
# 6qtPSRuwoxaVwSDw2QFJ8hp4RGHKsDAMRLgaRBhBM7e9A3/k7bA541DrWt19Cq5d
# IY1LUII3pVolF3YUtot7wFU2BbfpM0WiDEPXDWBUAvHNF0FDDukwuXUtn9J2n1f/
# 8EzDznON1GuNhrPP7cWJh6hywJgBzeR7ZHf2tsk76sKqY75u+qWoe4xQJXK7V2N7
# UJW7i6YC2W+/LrOaUYB9JykD88Jk+OJ2eLDtLSqzYAnJXYTIq7/mju5E8twyNZrN
# tQHqKUxUKhkeVgezgKoc4t12dgkTryl9efMy3qyxNesN34RR2i6eK8+6UtiW2ae5
# GESynl96l1E9+UWlRQIDAQABo0YwRDAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAww
# CgYIKwYBBQUHAwMwHQYDVR0OBBYEFEooM+aK7XCOIsSi0oFRhXyVQqdzMA0GCSqG
# SIb3DQEBCwUAA4IBgQC08zIpMh0vUuvfMcIUpwX3lABvT3V9Rf6swy8xuWHjJyJz
# hZVt0hOHeCBWF2RxYeJ2iY4hyH4FSkwwLCHmmM6kV3eLY2uibsYCUdwm1mwbtSws
# i4YAzGZF0Ueap2TC94d9O/dcpzYILKPdJwqAd3MprkWEbyFSfEkhy5NCmxZ2wQFd
# LtOU6YHMI9v6P8tIhGXpZbp3QjK9mZif6LZ9ZgXEzi4whxDwQ2RMTUVaf7kamyjc
# gGmO32gRcNr0qsGwTog7TUTcbTd/RVc0DEUMMrUZVWMcBwrBIFUWqnD4i/oZuHdH
# pMytQjZQcZBOzrJ/YcWxMNmdf09gq44kFs1QHiG+FFnATyglOs8SR3fJwJdPI+KN
# qpK0zo9FhCyl37qSpKpyS9QNZdl+isj7YQncfqCmadjY1y6nZhLzaEoDW0oHdv/s
# NzjZ54ieDALCH69wCbeCYk1lrI3ggu0t22QG1sHN7NmOm3T6SL2w7cF+TpeYXIfv
# FCGIHWHVGbQtK/TtwJMxggJmMIICYgIBATA0MCAxHjAcBgNVBAMMFXdvcmtwbGFj
# ZWNsb3VkaHViLmNvbQIQcCHy1SICVr9BhVbE7MrPTzANBglghkgBZQMEAgEFAKCB
# hDAYBgorBgEEAYI3AgEMMQowCKACgAChAoAAMBkGCSqGSIb3DQEJAzEMBgorBgEE
# AYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3DQEJ
# BDEiBCCNBv8eFI2prhlGFfzk8+yPDxHqy6UrFBbcM1kKKeHQFjANBgkqhkiG9w0B
# AQEFAASCAYAraS8qrz8k7CO4VbPNQkUPTDQW1oqBGKq9CzeBBdV+Nl5smbyQdvuX
# 6lMALSEhVd0RrIRr3VHLW/9OrPx5YCpCoEoRg3Omzm/DAGnjwfKJBJWEv0iD2Yy+
# /CgEGZvckbft5CgO7B59ZVDYrBPylj9hIP6hCptQs8SVnMfLrzhIPzZmrzJgMDZ4
# CX9UVSt7zZLD5BSAh58rgrK32h3uHQSWEoSQZAMZqmW2AzbCyO+78Q8Ufa4t1hIr
# 2YaCJctDUeuHPmBvEf654aBnoOx7KpPROIBjnlLRDdFc0/xgTd5A/wuroDLauQxC
# k5XoPwFzl3ePI4U3BPTrhs9WhDOSt9To5B97eCc9pTEd68jPSST4ghV/ZhS+ZSW1
# 7Ozn7TGSJMKiGKdICluQEi5vg2Ruog8+ca9eI5ySI7cAYldp6fiRVWKxwMDsM7GX
# Z4Bv9hSbbJpLK6BgNHdARdicOkwSvrVbSCL2dZUrRpbVXPJ7ShZRvBhA1XbP4Y1S
# sJDb3FYL1rQ=
# SIG # End signature block
