<#
.SYNOPSIS
Generates the SmartInventory\LaunchersByOrchestrator launchers from the jobs manifest template.

.DESCRIPTION
Each launcher submits one job through SmartM365-Inventory-Pipeline.ps1 -Job ... -Collect: the
resident orchestrators run it on its elected server with their shared claims, locks and
dependency rules, and the launcher waits for the result. A generic launcher accepts one or more
job names. Launchers are generated for every non-manual job of the template; a job that is
disabled in the shared manifest is refused at submission time.

With -Check the script only compares the expected launchers with the folder and exits 1 when
they differ (used by the offline tests).

.PARAMETER Check
Compares without writing.

.VERSION
1.0
#>
#requires -Version 7.2
[CmdletBinding()]
param([switch]$Check)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$tenantContextPath = Join-Path -Path $PSScriptRoot -ChildPath '..\..\Config\SmartM365-TenantContext.ps1'
if (-not (Test-Path -LiteralPath $tenantContextPath -PathType Leaf)) { throw "SmartM365 tenant context not found: $tenantContextPath" }
. $tenantContextPath
Write-SmartM365StartupBanner

$templatePath = Join-Path -Path $PSScriptRoot -ChildPath 'Orchestrator-Jobs.json.template'
$launcherRoot = Join-Path -Path (Split-Path -Path $PSScriptRoot -Parent) -ChildPath 'LaunchersByOrchestrator'
$template = Get-Content -LiteralPath $templatePath -Raw | ConvertFrom-Json -Depth 100

$pwshBlock = @'
set "PWSH="
set "PWSH_X64=%ProgramFiles%\PowerShell\7\pwsh.exe"
set "PWSH_X86="
if not "%ProgramFiles(x86)%"=="" set "PWSH_X86=%ProgramFiles(x86)%\PowerShell\7\pwsh.exe"
if exist "%PWSH_X64%" set "PWSH=%PWSH_X64%"
if not defined PWSH if defined PWSH_X86 if exist "%PWSH_X86%" set "PWSH=%PWSH_X86%"
if not defined PWSH for /f "delims=" %%I in ('where pwsh.exe 2^>nul') do if not defined PWSH set "PWSH=%%I"
if not defined PWSH (
    echo PowerShell 7 ^(pwsh.exe^) was not found.
    echo Install PowerShell 7 or add pwsh.exe to PATH.
    pause
    exit /b 1
)
'@

$expected = [ordered]@{}
foreach ($job in @($template.Jobs | Sort-Object Name)) {
    $mode = if ($job.PSObject.Properties['AssignmentMode'] -and $job.AssignmentMode) { [string]$job.AssignmentMode } else { 'Legacy' }
    if ($mode -eq 'Manual') { continue }
    $name = [string]$job.Name
    if ($name -notmatch '^[A-Za-z0-9._-]+$') { throw "Job name not usable in a launcher: $name" }
    $expected["Request-$name.cmd"] = @"
@echo off
setlocal EnableExtensions EnableDelayedExpansion
rem Generated by Orchestrator\New-SmartM365-OrchestratorJobLaunchers.ps1. Do not edit.
rem Requests job $name through the resident orchestrators (elected server, shared locks and
rem dependency rules) and waits for its result. Optional: -IncludeDependencies, -NoWait.

set "SCRIPT_DIR=%~dp0..\Orchestrator\"
$pwshBlock

"%PWSH%" -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT_DIR%SmartM365-Inventory-Pipeline.ps1" -Tenant prod -Job "$name" -Collect %*
set "EXIT_CODE=%ERRORLEVEL%"
exit /b %EXIT_CODE%
"@
}
$expected['Request-SmartM365-OrchestratorJob.cmd'] = @"
@echo off
setlocal EnableExtensions EnableDelayedExpansion
rem Generated by Orchestrator\New-SmartM365-OrchestratorJobLaunchers.ps1. Do not edit.
rem Usage: Request-SmartM365-OrchestratorJob.cmd JobName[,JobName...] [-IncludeDependencies] [-NoWait]
rem Requests the named jobs through the resident orchestrators and waits for their result.

if "%~1"=="" (
    echo Usage: %~nx0 JobName[,JobName...] [-IncludeDependencies] [-NoWait]
    exit /b 1
)
set "SCRIPT_DIR=%~dp0..\Orchestrator\"
$pwshBlock

"%PWSH%" -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT_DIR%SmartM365-Inventory-Pipeline.ps1" -Tenant prod -Collect -Job %*
set "EXIT_CODE=%ERRORLEVEL%"
exit /b %EXIT_CODE%
"@

$differences = [Collections.Generic.List[string]]::new()
$existing = if (Test-Path -LiteralPath $launcherRoot -PathType Container) { @(Get-ChildItem -LiteralPath $launcherRoot -File -Filter '*.cmd' | ForEach-Object Name) } else { @() }
foreach ($fileName in $expected.Keys) {
    $path = Join-Path -Path $launcherRoot -ChildPath $fileName
    $content = ($expected[$fileName] -replace "`r?`n", "`r`n").TrimEnd() + "`r`n"
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { $differences.Add("missing: $fileName") }
    elseif ([IO.File]::ReadAllText($path) -cne $content) { $differences.Add("outdated: $fileName") }
    if (-not $Check) {
        if (-not (Test-Path -LiteralPath $launcherRoot)) { New-Item -ItemType Directory -Path $launcherRoot -Force | Out-Null }
        [IO.File]::WriteAllText($path, $content, [Text.Encoding]::ASCII)
    }
}
foreach ($fileName in @($existing | Where-Object { -not $expected.Contains($_) })) {
    $differences.Add("obsolete: $fileName")
    if (-not $Check) { Remove-Item -LiteralPath (Join-Path -Path $launcherRoot -ChildPath $fileName) -Force }
}

if ($Check) {
    if ($differences.Count -gt 0) {
        $differences | ForEach-Object { Write-Output $_ }
        Write-Output ("LaunchersByOrchestrator is out of date ({0} difference(s)). Run New-SmartM365-OrchestratorJobLaunchers.ps1." -f $differences.Count)
        exit 1
    }
    Write-Output ("LaunchersByOrchestrator is up to date: {0} launcher(s)." -f $expected.Count)
    exit 0
}
Write-Output ("LaunchersByOrchestrator generated: {0} launcher(s); {1} change(s)." -f $expected.Count, $differences.Count)
